// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AuditLog is the predicate function for auditlog builders.
type AuditLog func(*sql.Selector)

// RepoPermission is the predicate function for repopermission builders.
type RepoPermission func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
