// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"api/internal/biz"
	"api/internal/conf"
	"api/internal/data"
	"api/internal/server"
	"api/internal/service"
	"github.com/bizjs/kratoscarf/auth/session"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, dockery *conf.Dockery, logger log.Logger) (*kratos.App, func(), error) {
	systemService := service.NewSystemService()
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData, logger)
	userUsecase := biz.NewUserUsecase(userRepo)
	auditRepo := data.NewAuditRepo(dataData, logger)
	auditUsecase := biz.NewAuditUsecase(auditRepo, logger)
	authService := service.NewAuthService(userUsecase, auditUsecase)
	permissionRepo := data.NewPermissionRepo(dataData, logger)
	permissionUsecase := biz.NewPermissionUsecase(permissionRepo, userRepo)
	userService := service.NewUserService(userUsecase, permissionUsecase, auditUsecase)
	permissionService := service.NewPermissionService(permissionUsecase, userUsecase, auditUsecase)
	keystoreConfig := biz.NewKeystoreConfigFromConf(dockery)
	keystore, err := biz.NewKeystore(keystoreConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	tokenIssuerConfig := biz.NewTokenIssuerConfigFromConf(dockery)
	tokenIssuer, err := biz.NewTokenIssuer(keystore, tokenIssuerConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	maintenance := biz.NewMaintenance()
	repoMetaRepo := data.NewRepoMetaRepo(dataData, logger)
	registryUpstreamURL := biz.NewRegistryUpstreamURL(dockery)
	client := biz.NewRegistryFetchClient(tokenIssuer, registryUpstreamURL)
	repoMetaUsecase := biz.NewRepoMetaUsecase(repoMetaRepo, client, logger)
	registryService := service.NewRegistryService(userUsecase, permissionUsecase, tokenIssuer, auditUsecase, maintenance, repoMetaUsecase, client, registryUpstreamURL)
	tokenService := service.NewTokenService(userUsecase, permissionUsecase, tokenIssuer, auditUsecase)
	gcConfig := biz.NewGCConfigFromConf(dockery)
	reconcilerConfig := biz.NewReconcilerConfigFromConf(dockery)
	reconciler := biz.NewReconciler(repoMetaUsecase, client, auditUsecase, reconcilerConfig, logger)
	gcRunner := biz.NewGCRunner(gcConfig, maintenance, auditUsecase, repoMetaUsecase, reconciler, logger)
	adminService := service.NewAdminService(auditUsecase, gcRunner)
	webhookSecretConfig := biz.NewWebhookSecretConfigFromConf(dockery)
	webhookSecret, err := biz.NewWebhookSecret(webhookSecretConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	webhookService := service.NewWebhookService(webhookSecret, repoMetaUsecase)
	services := &service.Services{
		System:     systemService,
		Auth:       authService,
		User:       userService,
		Permission: permissionService,
		Registry:   registryService,
		Token:      tokenService,
		Admin:      adminService,
		Webhook:    webhookService,
	}
	memoryStore := session.NewMemoryStore()
	config := biz.NewSessionConfigFromConf(dockery)
	manager := biz.NewSessionManager(memoryStore, config)
	httpServer := server.NewHTTPServer(confServer, services, manager, logger)
	app := newApp(logger, httpServer, userUsecase, repoMetaUsecase, reconciler, dockery)
	return app, func() {
		cleanup()
	}, nil
}
