// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"api/internal/biz"
	"api/internal/conf"
	"api/internal/data"
	"api/internal/server"
	"api/internal/service"

	"github.com/bizjs/kratoscarf/auth/session"

	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, dockery *conf.Dockery, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData, logger)
	permissionRepo := data.NewPermissionRepo(dataData, logger)
	userUsecase := biz.NewUserUsecase(userRepo)
	permissionUsecase := biz.NewPermissionUsecase(permissionRepo, userRepo)

	keystoreCfg := biz.NewKeystoreConfigFromConf(dockery)
	keystore, err := biz.NewKeystore(keystoreCfg)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	tokenIssuerCfg := biz.NewTokenIssuerConfigFromConf(dockery)
	tokenIssuer, err := biz.NewTokenIssuer(keystore, tokenIssuerCfg)
	if err != nil {
		cleanup()
		return nil, nil, err
	}

	sessionStore := session.NewMemoryStore()
	sessionCfg := biz.NewSessionConfigFromConf(dockery)
	sessionManager := session.NewManager(sessionStore, sessionCfg)

	systemService := service.NewSystemService()
	authService := service.NewAuthService(userUsecase)
	userService := service.NewUserService(userUsecase, permissionUsecase)
	permissionService := service.NewPermissionService(permissionUsecase, userUsecase)
	registryService := service.NewRegistryService()
	tokenService := service.NewTokenService(userUsecase, permissionUsecase, tokenIssuer)
	adminService := service.NewAdminService()
	services := &service.Services{
		System:     systemService,
		Auth:       authService,
		User:       userService,
		Permission: permissionService,
		Registry:   registryService,
		Token:      tokenService,
		Admin:      adminService,
	}
	httpServer := server.NewHTTPServer(confServer, services, sessionManager, logger)
	app := newApp(logger, httpServer, userUsecase, dockery)
	return app, func() {
		cleanup()
	}, nil
}
