// Code generated by ent, DO NOT EDIT.

package repometa

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the repometa type in the database.
	Label = "repo_meta"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRepo holds the string denoting the repo field in the database.
	FieldRepo = "repo"
	// FieldLatestTag holds the string denoting the latest_tag field in the database.
	FieldLatestTag = "latest_tag"
	// FieldTagCount holds the string denoting the tag_count field in the database.
	FieldTagCount = "tag_count"
	// FieldSize holds the string denoting the size field in the database.
	FieldSize = "size"
	// FieldCreated holds the string denoting the created field in the database.
	FieldCreated = "created"
	// FieldPlatforms holds the string denoting the platforms field in the database.
	FieldPlatforms = "platforms"
	// FieldPullCount holds the string denoting the pull_count field in the database.
	FieldPullCount = "pull_count"
	// FieldLastPulledAt holds the string denoting the last_pulled_at field in the database.
	FieldLastPulledAt = "last_pulled_at"
	// FieldRefreshedAt holds the string denoting the refreshed_at field in the database.
	FieldRefreshedAt = "refreshed_at"
	// Table holds the table name of the repometa in the database.
	Table = "repo_meta"
)

// Columns holds all SQL columns for repometa fields.
var Columns = []string{
	FieldID,
	FieldRepo,
	FieldLatestTag,
	FieldTagCount,
	FieldSize,
	FieldCreated,
	FieldPlatforms,
	FieldPullCount,
	FieldLastPulledAt,
	FieldRefreshedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// RepoValidator is a validator for the "repo" field. It is called by the builders before save.
	RepoValidator func(string) error
	// DefaultTagCount holds the default value on creation for the "tag_count" field.
	DefaultTagCount int
	// DefaultSize holds the default value on creation for the "size" field.
	DefaultSize int64
	// DefaultPullCount holds the default value on creation for the "pull_count" field.
	DefaultPullCount int64
	// DefaultRefreshedAt holds the default value on creation for the "refreshed_at" field.
	DefaultRefreshedAt func() time.Time
	// UpdateDefaultRefreshedAt holds the default value on update for the "refreshed_at" field.
	UpdateDefaultRefreshedAt func() time.Time
)

// OrderOption defines the ordering options for the RepoMeta queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRepo orders the results by the repo field.
func ByRepo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRepo, opts...).ToFunc()
}

// ByLatestTag orders the results by the latest_tag field.
func ByLatestTag(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLatestTag, opts...).ToFunc()
}

// ByTagCount orders the results by the tag_count field.
func ByTagCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTagCount, opts...).ToFunc()
}

// BySize orders the results by the size field.
func BySize(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSize, opts...).ToFunc()
}

// ByCreated orders the results by the created field.
func ByCreated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreated, opts...).ToFunc()
}

// ByPullCount orders the results by the pull_count field.
func ByPullCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPullCount, opts...).ToFunc()
}

// ByLastPulledAt orders the results by the last_pulled_at field.
func ByLastPulledAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastPulledAt, opts...).ToFunc()
}

// ByRefreshedAt orders the results by the refreshed_at field.
func ByRefreshedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRefreshedAt, opts...).ToFunc()
}
