// Code generated by ent, DO NOT EDIT.

package repometa

import (
	"api/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldLTE(FieldID, id))
}

// Repo applies equality check predicate on the "repo" field. It's identical to RepoEQ.
func Repo(v string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldEQ(FieldRepo, v))
}

// LatestTag applies equality check predicate on the "latest_tag" field. It's identical to LatestTagEQ.
func LatestTag(v string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldEQ(FieldLatestTag, v))
}

// TagCount applies equality check predicate on the "tag_count" field. It's identical to TagCountEQ.
func TagCount(v int) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldEQ(FieldTagCount, v))
}

// Size applies equality check predicate on the "size" field. It's identical to SizeEQ.
func Size(v int64) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldEQ(FieldSize, v))
}

// Created applies equality check predicate on the "created" field. It's identical to CreatedEQ.
func Created(v string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldEQ(FieldCreated, v))
}

// PullCount applies equality check predicate on the "pull_count" field. It's identical to PullCountEQ.
func PullCount(v int64) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldEQ(FieldPullCount, v))
}

// LastPulledAt applies equality check predicate on the "last_pulled_at" field. It's identical to LastPulledAtEQ.
func LastPulledAt(v time.Time) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldEQ(FieldLastPulledAt, v))
}

// RefreshedAt applies equality check predicate on the "refreshed_at" field. It's identical to RefreshedAtEQ.
func RefreshedAt(v time.Time) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldEQ(FieldRefreshedAt, v))
}

// RepoEQ applies the EQ predicate on the "repo" field.
func RepoEQ(v string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldEQ(FieldRepo, v))
}

// RepoNEQ applies the NEQ predicate on the "repo" field.
func RepoNEQ(v string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldNEQ(FieldRepo, v))
}

// RepoIn applies the In predicate on the "repo" field.
func RepoIn(vs ...string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldIn(FieldRepo, vs...))
}

// RepoNotIn applies the NotIn predicate on the "repo" field.
func RepoNotIn(vs ...string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldNotIn(FieldRepo, vs...))
}

// RepoGT applies the GT predicate on the "repo" field.
func RepoGT(v string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldGT(FieldRepo, v))
}

// RepoGTE applies the GTE predicate on the "repo" field.
func RepoGTE(v string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldGTE(FieldRepo, v))
}

// RepoLT applies the LT predicate on the "repo" field.
func RepoLT(v string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldLT(FieldRepo, v))
}

// RepoLTE applies the LTE predicate on the "repo" field.
func RepoLTE(v string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldLTE(FieldRepo, v))
}

// RepoContains applies the Contains predicate on the "repo" field.
func RepoContains(v string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldContains(FieldRepo, v))
}

// RepoHasPrefix applies the HasPrefix predicate on the "repo" field.
func RepoHasPrefix(v string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldHasPrefix(FieldRepo, v))
}

// RepoHasSuffix applies the HasSuffix predicate on the "repo" field.
func RepoHasSuffix(v string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldHasSuffix(FieldRepo, v))
}

// RepoEqualFold applies the EqualFold predicate on the "repo" field.
func RepoEqualFold(v string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldEqualFold(FieldRepo, v))
}

// RepoContainsFold applies the ContainsFold predicate on the "repo" field.
func RepoContainsFold(v string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldContainsFold(FieldRepo, v))
}

// LatestTagEQ applies the EQ predicate on the "latest_tag" field.
func LatestTagEQ(v string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldEQ(FieldLatestTag, v))
}

// LatestTagNEQ applies the NEQ predicate on the "latest_tag" field.
func LatestTagNEQ(v string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldNEQ(FieldLatestTag, v))
}

// LatestTagIn applies the In predicate on the "latest_tag" field.
func LatestTagIn(vs ...string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldIn(FieldLatestTag, vs...))
}

// LatestTagNotIn applies the NotIn predicate on the "latest_tag" field.
func LatestTagNotIn(vs ...string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldNotIn(FieldLatestTag, vs...))
}

// LatestTagGT applies the GT predicate on the "latest_tag" field.
func LatestTagGT(v string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldGT(FieldLatestTag, v))
}

// LatestTagGTE applies the GTE predicate on the "latest_tag" field.
func LatestTagGTE(v string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldGTE(FieldLatestTag, v))
}

// LatestTagLT applies the LT predicate on the "latest_tag" field.
func LatestTagLT(v string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldLT(FieldLatestTag, v))
}

// LatestTagLTE applies the LTE predicate on the "latest_tag" field.
func LatestTagLTE(v string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldLTE(FieldLatestTag, v))
}

// LatestTagContains applies the Contains predicate on the "latest_tag" field.
func LatestTagContains(v string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldContains(FieldLatestTag, v))
}

// LatestTagHasPrefix applies the HasPrefix predicate on the "latest_tag" field.
func LatestTagHasPrefix(v string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldHasPrefix(FieldLatestTag, v))
}

// LatestTagHasSuffix applies the HasSuffix predicate on the "latest_tag" field.
func LatestTagHasSuffix(v string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldHasSuffix(FieldLatestTag, v))
}

// LatestTagIsNil applies the IsNil predicate on the "latest_tag" field.
func LatestTagIsNil() predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldIsNull(FieldLatestTag))
}

// LatestTagNotNil applies the NotNil predicate on the "latest_tag" field.
func LatestTagNotNil() predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldNotNull(FieldLatestTag))
}

// LatestTagEqualFold applies the EqualFold predicate on the "latest_tag" field.
func LatestTagEqualFold(v string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldEqualFold(FieldLatestTag, v))
}

// LatestTagContainsFold applies the ContainsFold predicate on the "latest_tag" field.
func LatestTagContainsFold(v string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldContainsFold(FieldLatestTag, v))
}

// TagCountEQ applies the EQ predicate on the "tag_count" field.
func TagCountEQ(v int) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldEQ(FieldTagCount, v))
}

// TagCountNEQ applies the NEQ predicate on the "tag_count" field.
func TagCountNEQ(v int) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldNEQ(FieldTagCount, v))
}

// TagCountIn applies the In predicate on the "tag_count" field.
func TagCountIn(vs ...int) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldIn(FieldTagCount, vs...))
}

// TagCountNotIn applies the NotIn predicate on the "tag_count" field.
func TagCountNotIn(vs ...int) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldNotIn(FieldTagCount, vs...))
}

// TagCountGT applies the GT predicate on the "tag_count" field.
func TagCountGT(v int) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldGT(FieldTagCount, v))
}

// TagCountGTE applies the GTE predicate on the "tag_count" field.
func TagCountGTE(v int) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldGTE(FieldTagCount, v))
}

// TagCountLT applies the LT predicate on the "tag_count" field.
func TagCountLT(v int) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldLT(FieldTagCount, v))
}

// TagCountLTE applies the LTE predicate on the "tag_count" field.
func TagCountLTE(v int) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldLTE(FieldTagCount, v))
}

// SizeEQ applies the EQ predicate on the "size" field.
func SizeEQ(v int64) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldEQ(FieldSize, v))
}

// SizeNEQ applies the NEQ predicate on the "size" field.
func SizeNEQ(v int64) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldNEQ(FieldSize, v))
}

// SizeIn applies the In predicate on the "size" field.
func SizeIn(vs ...int64) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldIn(FieldSize, vs...))
}

// SizeNotIn applies the NotIn predicate on the "size" field.
func SizeNotIn(vs ...int64) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldNotIn(FieldSize, vs...))
}

// SizeGT applies the GT predicate on the "size" field.
func SizeGT(v int64) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldGT(FieldSize, v))
}

// SizeGTE applies the GTE predicate on the "size" field.
func SizeGTE(v int64) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldGTE(FieldSize, v))
}

// SizeLT applies the LT predicate on the "size" field.
func SizeLT(v int64) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldLT(FieldSize, v))
}

// SizeLTE applies the LTE predicate on the "size" field.
func SizeLTE(v int64) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldLTE(FieldSize, v))
}

// CreatedEQ applies the EQ predicate on the "created" field.
func CreatedEQ(v string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldEQ(FieldCreated, v))
}

// CreatedNEQ applies the NEQ predicate on the "created" field.
func CreatedNEQ(v string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldNEQ(FieldCreated, v))
}

// CreatedIn applies the In predicate on the "created" field.
func CreatedIn(vs ...string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldIn(FieldCreated, vs...))
}

// CreatedNotIn applies the NotIn predicate on the "created" field.
func CreatedNotIn(vs ...string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldNotIn(FieldCreated, vs...))
}

// CreatedGT applies the GT predicate on the "created" field.
func CreatedGT(v string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldGT(FieldCreated, v))
}

// CreatedGTE applies the GTE predicate on the "created" field.
func CreatedGTE(v string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldGTE(FieldCreated, v))
}

// CreatedLT applies the LT predicate on the "created" field.
func CreatedLT(v string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldLT(FieldCreated, v))
}

// CreatedLTE applies the LTE predicate on the "created" field.
func CreatedLTE(v string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldLTE(FieldCreated, v))
}

// CreatedContains applies the Contains predicate on the "created" field.
func CreatedContains(v string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldContains(FieldCreated, v))
}

// CreatedHasPrefix applies the HasPrefix predicate on the "created" field.
func CreatedHasPrefix(v string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldHasPrefix(FieldCreated, v))
}

// CreatedHasSuffix applies the HasSuffix predicate on the "created" field.
func CreatedHasSuffix(v string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldHasSuffix(FieldCreated, v))
}

// CreatedIsNil applies the IsNil predicate on the "created" field.
func CreatedIsNil() predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldIsNull(FieldCreated))
}

// CreatedNotNil applies the NotNil predicate on the "created" field.
func CreatedNotNil() predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldNotNull(FieldCreated))
}

// CreatedEqualFold applies the EqualFold predicate on the "created" field.
func CreatedEqualFold(v string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldEqualFold(FieldCreated, v))
}

// CreatedContainsFold applies the ContainsFold predicate on the "created" field.
func CreatedContainsFold(v string) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldContainsFold(FieldCreated, v))
}

// PlatformsIsNil applies the IsNil predicate on the "platforms" field.
func PlatformsIsNil() predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldIsNull(FieldPlatforms))
}

// PlatformsNotNil applies the NotNil predicate on the "platforms" field.
func PlatformsNotNil() predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldNotNull(FieldPlatforms))
}

// PullCountEQ applies the EQ predicate on the "pull_count" field.
func PullCountEQ(v int64) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldEQ(FieldPullCount, v))
}

// PullCountNEQ applies the NEQ predicate on the "pull_count" field.
func PullCountNEQ(v int64) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldNEQ(FieldPullCount, v))
}

// PullCountIn applies the In predicate on the "pull_count" field.
func PullCountIn(vs ...int64) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldIn(FieldPullCount, vs...))
}

// PullCountNotIn applies the NotIn predicate on the "pull_count" field.
func PullCountNotIn(vs ...int64) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldNotIn(FieldPullCount, vs...))
}

// PullCountGT applies the GT predicate on the "pull_count" field.
func PullCountGT(v int64) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldGT(FieldPullCount, v))
}

// PullCountGTE applies the GTE predicate on the "pull_count" field.
func PullCountGTE(v int64) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldGTE(FieldPullCount, v))
}

// PullCountLT applies the LT predicate on the "pull_count" field.
func PullCountLT(v int64) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldLT(FieldPullCount, v))
}

// PullCountLTE applies the LTE predicate on the "pull_count" field.
func PullCountLTE(v int64) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldLTE(FieldPullCount, v))
}

// LastPulledAtEQ applies the EQ predicate on the "last_pulled_at" field.
func LastPulledAtEQ(v time.Time) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldEQ(FieldLastPulledAt, v))
}

// LastPulledAtNEQ applies the NEQ predicate on the "last_pulled_at" field.
func LastPulledAtNEQ(v time.Time) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldNEQ(FieldLastPulledAt, v))
}

// LastPulledAtIn applies the In predicate on the "last_pulled_at" field.
func LastPulledAtIn(vs ...time.Time) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldIn(FieldLastPulledAt, vs...))
}

// LastPulledAtNotIn applies the NotIn predicate on the "last_pulled_at" field.
func LastPulledAtNotIn(vs ...time.Time) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldNotIn(FieldLastPulledAt, vs...))
}

// LastPulledAtGT applies the GT predicate on the "last_pulled_at" field.
func LastPulledAtGT(v time.Time) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldGT(FieldLastPulledAt, v))
}

// LastPulledAtGTE applies the GTE predicate on the "last_pulled_at" field.
func LastPulledAtGTE(v time.Time) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldGTE(FieldLastPulledAt, v))
}

// LastPulledAtLT applies the LT predicate on the "last_pulled_at" field.
func LastPulledAtLT(v time.Time) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldLT(FieldLastPulledAt, v))
}

// LastPulledAtLTE applies the LTE predicate on the "last_pulled_at" field.
func LastPulledAtLTE(v time.Time) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldLTE(FieldLastPulledAt, v))
}

// LastPulledAtIsNil applies the IsNil predicate on the "last_pulled_at" field.
func LastPulledAtIsNil() predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldIsNull(FieldLastPulledAt))
}

// LastPulledAtNotNil applies the NotNil predicate on the "last_pulled_at" field.
func LastPulledAtNotNil() predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldNotNull(FieldLastPulledAt))
}

// RefreshedAtEQ applies the EQ predicate on the "refreshed_at" field.
func RefreshedAtEQ(v time.Time) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldEQ(FieldRefreshedAt, v))
}

// RefreshedAtNEQ applies the NEQ predicate on the "refreshed_at" field.
func RefreshedAtNEQ(v time.Time) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldNEQ(FieldRefreshedAt, v))
}

// RefreshedAtIn applies the In predicate on the "refreshed_at" field.
func RefreshedAtIn(vs ...time.Time) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldIn(FieldRefreshedAt, vs...))
}

// RefreshedAtNotIn applies the NotIn predicate on the "refreshed_at" field.
func RefreshedAtNotIn(vs ...time.Time) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldNotIn(FieldRefreshedAt, vs...))
}

// RefreshedAtGT applies the GT predicate on the "refreshed_at" field.
func RefreshedAtGT(v time.Time) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldGT(FieldRefreshedAt, v))
}

// RefreshedAtGTE applies the GTE predicate on the "refreshed_at" field.
func RefreshedAtGTE(v time.Time) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldGTE(FieldRefreshedAt, v))
}

// RefreshedAtLT applies the LT predicate on the "refreshed_at" field.
func RefreshedAtLT(v time.Time) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldLT(FieldRefreshedAt, v))
}

// RefreshedAtLTE applies the LTE predicate on the "refreshed_at" field.
func RefreshedAtLTE(v time.Time) predicate.RepoMeta {
	return predicate.RepoMeta(sql.FieldLTE(FieldRefreshedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RepoMeta) predicate.RepoMeta {
	return predicate.RepoMeta(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RepoMeta) predicate.RepoMeta {
	return predicate.RepoMeta(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RepoMeta) predicate.RepoMeta {
	return predicate.RepoMeta(sql.NotPredicates(p))
}
