// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/internal/data/ent/auditlog"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AuditLogCreate is the builder for creating a AuditLog entity.
type AuditLogCreate struct {
	config
	mutation *AuditLogMutation
	hooks    []Hook
}

// SetTs sets the "ts" field.
func (alc *AuditLogCreate) SetTs(t time.Time) *AuditLogCreate {
	alc.mutation.SetTs(t)
	return alc
}

// SetNillableTs sets the "ts" field if the given value is not nil.
func (alc *AuditLogCreate) SetNillableTs(t *time.Time) *AuditLogCreate {
	if t != nil {
		alc.SetTs(*t)
	}
	return alc
}

// SetActor sets the "actor" field.
func (alc *AuditLogCreate) SetActor(s string) *AuditLogCreate {
	alc.mutation.SetActor(s)
	return alc
}

// SetAction sets the "action" field.
func (alc *AuditLogCreate) SetAction(s string) *AuditLogCreate {
	alc.mutation.SetAction(s)
	return alc
}

// SetTarget sets the "target" field.
func (alc *AuditLogCreate) SetTarget(s string) *AuditLogCreate {
	alc.mutation.SetTarget(s)
	return alc
}

// SetNillableTarget sets the "target" field if the given value is not nil.
func (alc *AuditLogCreate) SetNillableTarget(s *string) *AuditLogCreate {
	if s != nil {
		alc.SetTarget(*s)
	}
	return alc
}

// SetScope sets the "scope" field.
func (alc *AuditLogCreate) SetScope(s string) *AuditLogCreate {
	alc.mutation.SetScope(s)
	return alc
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (alc *AuditLogCreate) SetNillableScope(s *string) *AuditLogCreate {
	if s != nil {
		alc.SetScope(*s)
	}
	return alc
}

// SetClientIP sets the "client_ip" field.
func (alc *AuditLogCreate) SetClientIP(s string) *AuditLogCreate {
	alc.mutation.SetClientIP(s)
	return alc
}

// SetNillableClientIP sets the "client_ip" field if the given value is not nil.
func (alc *AuditLogCreate) SetNillableClientIP(s *string) *AuditLogCreate {
	if s != nil {
		alc.SetClientIP(*s)
	}
	return alc
}

// SetSuccess sets the "success" field.
func (alc *AuditLogCreate) SetSuccess(b bool) *AuditLogCreate {
	alc.mutation.SetSuccess(b)
	return alc
}

// SetNillableSuccess sets the "success" field if the given value is not nil.
func (alc *AuditLogCreate) SetNillableSuccess(b *bool) *AuditLogCreate {
	if b != nil {
		alc.SetSuccess(*b)
	}
	return alc
}

// SetDetail sets the "detail" field.
func (alc *AuditLogCreate) SetDetail(m map[string]interface{}) *AuditLogCreate {
	alc.mutation.SetDetail(m)
	return alc
}

// Mutation returns the AuditLogMutation object of the builder.
func (alc *AuditLogCreate) Mutation() *AuditLogMutation {
	return alc.mutation
}

// Save creates the AuditLog in the database.
func (alc *AuditLogCreate) Save(ctx context.Context) (*AuditLog, error) {
	alc.defaults()
	return withHooks(ctx, alc.sqlSave, alc.mutation, alc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (alc *AuditLogCreate) SaveX(ctx context.Context) *AuditLog {
	v, err := alc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (alc *AuditLogCreate) Exec(ctx context.Context) error {
	_, err := alc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (alc *AuditLogCreate) ExecX(ctx context.Context) {
	if err := alc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (alc *AuditLogCreate) defaults() {
	if _, ok := alc.mutation.Ts(); !ok {
		v := auditlog.DefaultTs()
		alc.mutation.SetTs(v)
	}
	if _, ok := alc.mutation.Success(); !ok {
		v := auditlog.DefaultSuccess
		alc.mutation.SetSuccess(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (alc *AuditLogCreate) check() error {
	if _, ok := alc.mutation.Ts(); !ok {
		return &ValidationError{Name: "ts", err: errors.New(`ent: missing required field "AuditLog.ts"`)}
	}
	if _, ok := alc.mutation.Actor(); !ok {
		return &ValidationError{Name: "actor", err: errors.New(`ent: missing required field "AuditLog.actor"`)}
	}
	if v, ok := alc.mutation.Actor(); ok {
		if err := auditlog.ActorValidator(v); err != nil {
			return &ValidationError{Name: "actor", err: fmt.Errorf(`ent: validator failed for field "AuditLog.actor": %w`, err)}
		}
	}
	if _, ok := alc.mutation.Action(); !ok {
		return &ValidationError{Name: "action", err: errors.New(`ent: missing required field "AuditLog.action"`)}
	}
	if v, ok := alc.mutation.Action(); ok {
		if err := auditlog.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "AuditLog.action": %w`, err)}
		}
	}
	if _, ok := alc.mutation.Success(); !ok {
		return &ValidationError{Name: "success", err: errors.New(`ent: missing required field "AuditLog.success"`)}
	}
	return nil
}

func (alc *AuditLogCreate) sqlSave(ctx context.Context) (*AuditLog, error) {
	if err := alc.check(); err != nil {
		return nil, err
	}
	_node, _spec := alc.createSpec()
	if err := sqlgraph.CreateNode(ctx, alc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	alc.mutation.id = &_node.ID
	alc.mutation.done = true
	return _node, nil
}

func (alc *AuditLogCreate) createSpec() (*AuditLog, *sqlgraph.CreateSpec) {
	var (
		_node = &AuditLog{config: alc.config}
		_spec = sqlgraph.NewCreateSpec(auditlog.Table, sqlgraph.NewFieldSpec(auditlog.FieldID, field.TypeInt))
	)
	if value, ok := alc.mutation.Ts(); ok {
		_spec.SetField(auditlog.FieldTs, field.TypeTime, value)
		_node.Ts = value
	}
	if value, ok := alc.mutation.Actor(); ok {
		_spec.SetField(auditlog.FieldActor, field.TypeString, value)
		_node.Actor = value
	}
	if value, ok := alc.mutation.Action(); ok {
		_spec.SetField(auditlog.FieldAction, field.TypeString, value)
		_node.Action = value
	}
	if value, ok := alc.mutation.Target(); ok {
		_spec.SetField(auditlog.FieldTarget, field.TypeString, value)
		_node.Target = value
	}
	if value, ok := alc.mutation.Scope(); ok {
		_spec.SetField(auditlog.FieldScope, field.TypeString, value)
		_node.Scope = value
	}
	if value, ok := alc.mutation.ClientIP(); ok {
		_spec.SetField(auditlog.FieldClientIP, field.TypeString, value)
		_node.ClientIP = value
	}
	if value, ok := alc.mutation.Success(); ok {
		_spec.SetField(auditlog.FieldSuccess, field.TypeBool, value)
		_node.Success = value
	}
	if value, ok := alc.mutation.Detail(); ok {
		_spec.SetField(auditlog.FieldDetail, field.TypeJSON, value)
		_node.Detail = value
	}
	return _node, _spec
}

// AuditLogCreateBulk is the builder for creating many AuditLog entities in bulk.
type AuditLogCreateBulk struct {
	config
	err      error
	builders []*AuditLogCreate
}

// Save creates the AuditLog entities in the database.
func (alcb *AuditLogCreateBulk) Save(ctx context.Context) ([]*AuditLog, error) {
	if alcb.err != nil {
		return nil, alcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(alcb.builders))
	nodes := make([]*AuditLog, len(alcb.builders))
	mutators := make([]Mutator, len(alcb.builders))
	for i := range alcb.builders {
		func(i int, root context.Context) {
			builder := alcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AuditLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, alcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, alcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, alcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (alcb *AuditLogCreateBulk) SaveX(ctx context.Context) []*AuditLog {
	v, err := alcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (alcb *AuditLogCreateBulk) Exec(ctx context.Context) error {
	_, err := alcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (alcb *AuditLogCreateBulk) ExecX(ctx context.Context) {
	if err := alcb.Exec(ctx); err != nil {
		panic(err)
	}
}
