// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/internal/data/ent/auditlog"
	"api/internal/data/ent/predicate"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AuditLogUpdate is the builder for updating AuditLog entities.
type AuditLogUpdate struct {
	config
	hooks    []Hook
	mutation *AuditLogMutation
}

// Where appends a list predicates to the AuditLogUpdate builder.
func (alu *AuditLogUpdate) Where(ps ...predicate.AuditLog) *AuditLogUpdate {
	alu.mutation.Where(ps...)
	return alu
}

// SetActor sets the "actor" field.
func (alu *AuditLogUpdate) SetActor(s string) *AuditLogUpdate {
	alu.mutation.SetActor(s)
	return alu
}

// SetNillableActor sets the "actor" field if the given value is not nil.
func (alu *AuditLogUpdate) SetNillableActor(s *string) *AuditLogUpdate {
	if s != nil {
		alu.SetActor(*s)
	}
	return alu
}

// SetAction sets the "action" field.
func (alu *AuditLogUpdate) SetAction(s string) *AuditLogUpdate {
	alu.mutation.SetAction(s)
	return alu
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (alu *AuditLogUpdate) SetNillableAction(s *string) *AuditLogUpdate {
	if s != nil {
		alu.SetAction(*s)
	}
	return alu
}

// SetTarget sets the "target" field.
func (alu *AuditLogUpdate) SetTarget(s string) *AuditLogUpdate {
	alu.mutation.SetTarget(s)
	return alu
}

// SetNillableTarget sets the "target" field if the given value is not nil.
func (alu *AuditLogUpdate) SetNillableTarget(s *string) *AuditLogUpdate {
	if s != nil {
		alu.SetTarget(*s)
	}
	return alu
}

// ClearTarget clears the value of the "target" field.
func (alu *AuditLogUpdate) ClearTarget() *AuditLogUpdate {
	alu.mutation.ClearTarget()
	return alu
}

// SetScope sets the "scope" field.
func (alu *AuditLogUpdate) SetScope(s string) *AuditLogUpdate {
	alu.mutation.SetScope(s)
	return alu
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (alu *AuditLogUpdate) SetNillableScope(s *string) *AuditLogUpdate {
	if s != nil {
		alu.SetScope(*s)
	}
	return alu
}

// ClearScope clears the value of the "scope" field.
func (alu *AuditLogUpdate) ClearScope() *AuditLogUpdate {
	alu.mutation.ClearScope()
	return alu
}

// SetClientIP sets the "client_ip" field.
func (alu *AuditLogUpdate) SetClientIP(s string) *AuditLogUpdate {
	alu.mutation.SetClientIP(s)
	return alu
}

// SetNillableClientIP sets the "client_ip" field if the given value is not nil.
func (alu *AuditLogUpdate) SetNillableClientIP(s *string) *AuditLogUpdate {
	if s != nil {
		alu.SetClientIP(*s)
	}
	return alu
}

// ClearClientIP clears the value of the "client_ip" field.
func (alu *AuditLogUpdate) ClearClientIP() *AuditLogUpdate {
	alu.mutation.ClearClientIP()
	return alu
}

// SetSuccess sets the "success" field.
func (alu *AuditLogUpdate) SetSuccess(b bool) *AuditLogUpdate {
	alu.mutation.SetSuccess(b)
	return alu
}

// SetNillableSuccess sets the "success" field if the given value is not nil.
func (alu *AuditLogUpdate) SetNillableSuccess(b *bool) *AuditLogUpdate {
	if b != nil {
		alu.SetSuccess(*b)
	}
	return alu
}

// SetDetail sets the "detail" field.
func (alu *AuditLogUpdate) SetDetail(m map[string]interface{}) *AuditLogUpdate {
	alu.mutation.SetDetail(m)
	return alu
}

// ClearDetail clears the value of the "detail" field.
func (alu *AuditLogUpdate) ClearDetail() *AuditLogUpdate {
	alu.mutation.ClearDetail()
	return alu
}

// Mutation returns the AuditLogMutation object of the builder.
func (alu *AuditLogUpdate) Mutation() *AuditLogMutation {
	return alu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (alu *AuditLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, alu.sqlSave, alu.mutation, alu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (alu *AuditLogUpdate) SaveX(ctx context.Context) int {
	affected, err := alu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (alu *AuditLogUpdate) Exec(ctx context.Context) error {
	_, err := alu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (alu *AuditLogUpdate) ExecX(ctx context.Context) {
	if err := alu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (alu *AuditLogUpdate) check() error {
	if v, ok := alu.mutation.Actor(); ok {
		if err := auditlog.ActorValidator(v); err != nil {
			return &ValidationError{Name: "actor", err: fmt.Errorf(`ent: validator failed for field "AuditLog.actor": %w`, err)}
		}
	}
	if v, ok := alu.mutation.Action(); ok {
		if err := auditlog.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "AuditLog.action": %w`, err)}
		}
	}
	return nil
}

func (alu *AuditLogUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := alu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(auditlog.Table, auditlog.Columns, sqlgraph.NewFieldSpec(auditlog.FieldID, field.TypeInt))
	if ps := alu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := alu.mutation.Actor(); ok {
		_spec.SetField(auditlog.FieldActor, field.TypeString, value)
	}
	if value, ok := alu.mutation.Action(); ok {
		_spec.SetField(auditlog.FieldAction, field.TypeString, value)
	}
	if value, ok := alu.mutation.Target(); ok {
		_spec.SetField(auditlog.FieldTarget, field.TypeString, value)
	}
	if alu.mutation.TargetCleared() {
		_spec.ClearField(auditlog.FieldTarget, field.TypeString)
	}
	if value, ok := alu.mutation.Scope(); ok {
		_spec.SetField(auditlog.FieldScope, field.TypeString, value)
	}
	if alu.mutation.ScopeCleared() {
		_spec.ClearField(auditlog.FieldScope, field.TypeString)
	}
	if value, ok := alu.mutation.ClientIP(); ok {
		_spec.SetField(auditlog.FieldClientIP, field.TypeString, value)
	}
	if alu.mutation.ClientIPCleared() {
		_spec.ClearField(auditlog.FieldClientIP, field.TypeString)
	}
	if value, ok := alu.mutation.Success(); ok {
		_spec.SetField(auditlog.FieldSuccess, field.TypeBool, value)
	}
	if value, ok := alu.mutation.Detail(); ok {
		_spec.SetField(auditlog.FieldDetail, field.TypeJSON, value)
	}
	if alu.mutation.DetailCleared() {
		_spec.ClearField(auditlog.FieldDetail, field.TypeJSON)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, alu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{auditlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	alu.mutation.done = true
	return n, nil
}

// AuditLogUpdateOne is the builder for updating a single AuditLog entity.
type AuditLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AuditLogMutation
}

// SetActor sets the "actor" field.
func (aluo *AuditLogUpdateOne) SetActor(s string) *AuditLogUpdateOne {
	aluo.mutation.SetActor(s)
	return aluo
}

// SetNillableActor sets the "actor" field if the given value is not nil.
func (aluo *AuditLogUpdateOne) SetNillableActor(s *string) *AuditLogUpdateOne {
	if s != nil {
		aluo.SetActor(*s)
	}
	return aluo
}

// SetAction sets the "action" field.
func (aluo *AuditLogUpdateOne) SetAction(s string) *AuditLogUpdateOne {
	aluo.mutation.SetAction(s)
	return aluo
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (aluo *AuditLogUpdateOne) SetNillableAction(s *string) *AuditLogUpdateOne {
	if s != nil {
		aluo.SetAction(*s)
	}
	return aluo
}

// SetTarget sets the "target" field.
func (aluo *AuditLogUpdateOne) SetTarget(s string) *AuditLogUpdateOne {
	aluo.mutation.SetTarget(s)
	return aluo
}

// SetNillableTarget sets the "target" field if the given value is not nil.
func (aluo *AuditLogUpdateOne) SetNillableTarget(s *string) *AuditLogUpdateOne {
	if s != nil {
		aluo.SetTarget(*s)
	}
	return aluo
}

// ClearTarget clears the value of the "target" field.
func (aluo *AuditLogUpdateOne) ClearTarget() *AuditLogUpdateOne {
	aluo.mutation.ClearTarget()
	return aluo
}

// SetScope sets the "scope" field.
func (aluo *AuditLogUpdateOne) SetScope(s string) *AuditLogUpdateOne {
	aluo.mutation.SetScope(s)
	return aluo
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (aluo *AuditLogUpdateOne) SetNillableScope(s *string) *AuditLogUpdateOne {
	if s != nil {
		aluo.SetScope(*s)
	}
	return aluo
}

// ClearScope clears the value of the "scope" field.
func (aluo *AuditLogUpdateOne) ClearScope() *AuditLogUpdateOne {
	aluo.mutation.ClearScope()
	return aluo
}

// SetClientIP sets the "client_ip" field.
func (aluo *AuditLogUpdateOne) SetClientIP(s string) *AuditLogUpdateOne {
	aluo.mutation.SetClientIP(s)
	return aluo
}

// SetNillableClientIP sets the "client_ip" field if the given value is not nil.
func (aluo *AuditLogUpdateOne) SetNillableClientIP(s *string) *AuditLogUpdateOne {
	if s != nil {
		aluo.SetClientIP(*s)
	}
	return aluo
}

// ClearClientIP clears the value of the "client_ip" field.
func (aluo *AuditLogUpdateOne) ClearClientIP() *AuditLogUpdateOne {
	aluo.mutation.ClearClientIP()
	return aluo
}

// SetSuccess sets the "success" field.
func (aluo *AuditLogUpdateOne) SetSuccess(b bool) *AuditLogUpdateOne {
	aluo.mutation.SetSuccess(b)
	return aluo
}

// SetNillableSuccess sets the "success" field if the given value is not nil.
func (aluo *AuditLogUpdateOne) SetNillableSuccess(b *bool) *AuditLogUpdateOne {
	if b != nil {
		aluo.SetSuccess(*b)
	}
	return aluo
}

// SetDetail sets the "detail" field.
func (aluo *AuditLogUpdateOne) SetDetail(m map[string]interface{}) *AuditLogUpdateOne {
	aluo.mutation.SetDetail(m)
	return aluo
}

// ClearDetail clears the value of the "detail" field.
func (aluo *AuditLogUpdateOne) ClearDetail() *AuditLogUpdateOne {
	aluo.mutation.ClearDetail()
	return aluo
}

// Mutation returns the AuditLogMutation object of the builder.
func (aluo *AuditLogUpdateOne) Mutation() *AuditLogMutation {
	return aluo.mutation
}

// Where appends a list predicates to the AuditLogUpdate builder.
func (aluo *AuditLogUpdateOne) Where(ps ...predicate.AuditLog) *AuditLogUpdateOne {
	aluo.mutation.Where(ps...)
	return aluo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (aluo *AuditLogUpdateOne) Select(field string, fields ...string) *AuditLogUpdateOne {
	aluo.fields = append([]string{field}, fields...)
	return aluo
}

// Save executes the query and returns the updated AuditLog entity.
func (aluo *AuditLogUpdateOne) Save(ctx context.Context) (*AuditLog, error) {
	return withHooks(ctx, aluo.sqlSave, aluo.mutation, aluo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (aluo *AuditLogUpdateOne) SaveX(ctx context.Context) *AuditLog {
	node, err := aluo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (aluo *AuditLogUpdateOne) Exec(ctx context.Context) error {
	_, err := aluo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (aluo *AuditLogUpdateOne) ExecX(ctx context.Context) {
	if err := aluo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (aluo *AuditLogUpdateOne) check() error {
	if v, ok := aluo.mutation.Actor(); ok {
		if err := auditlog.ActorValidator(v); err != nil {
			return &ValidationError{Name: "actor", err: fmt.Errorf(`ent: validator failed for field "AuditLog.actor": %w`, err)}
		}
	}
	if v, ok := aluo.mutation.Action(); ok {
		if err := auditlog.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "AuditLog.action": %w`, err)}
		}
	}
	return nil
}

func (aluo *AuditLogUpdateOne) sqlSave(ctx context.Context) (_node *AuditLog, err error) {
	if err := aluo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(auditlog.Table, auditlog.Columns, sqlgraph.NewFieldSpec(auditlog.FieldID, field.TypeInt))
	id, ok := aluo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AuditLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := aluo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, auditlog.FieldID)
		for _, f := range fields {
			if !auditlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != auditlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := aluo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := aluo.mutation.Actor(); ok {
		_spec.SetField(auditlog.FieldActor, field.TypeString, value)
	}
	if value, ok := aluo.mutation.Action(); ok {
		_spec.SetField(auditlog.FieldAction, field.TypeString, value)
	}
	if value, ok := aluo.mutation.Target(); ok {
		_spec.SetField(auditlog.FieldTarget, field.TypeString, value)
	}
	if aluo.mutation.TargetCleared() {
		_spec.ClearField(auditlog.FieldTarget, field.TypeString)
	}
	if value, ok := aluo.mutation.Scope(); ok {
		_spec.SetField(auditlog.FieldScope, field.TypeString, value)
	}
	if aluo.mutation.ScopeCleared() {
		_spec.ClearField(auditlog.FieldScope, field.TypeString)
	}
	if value, ok := aluo.mutation.ClientIP(); ok {
		_spec.SetField(auditlog.FieldClientIP, field.TypeString, value)
	}
	if aluo.mutation.ClientIPCleared() {
		_spec.ClearField(auditlog.FieldClientIP, field.TypeString)
	}
	if value, ok := aluo.mutation.Success(); ok {
		_spec.SetField(auditlog.FieldSuccess, field.TypeBool, value)
	}
	if value, ok := aluo.mutation.Detail(); ok {
		_spec.SetField(auditlog.FieldDetail, field.TypeJSON, value)
	}
	if aluo.mutation.DetailCleared() {
		_spec.ClearField(auditlog.FieldDetail, field.TypeJSON)
	}
	_node = &AuditLog{config: aluo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, aluo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{auditlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	aluo.mutation.done = true
	return _node, nil
}
