// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/internal/data/ent/predicate"
	"api/internal/data/ent/repopermission"
	"api/internal/data/ent/user"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RepoPermissionUpdate is the builder for updating RepoPermission entities.
type RepoPermissionUpdate struct {
	config
	hooks    []Hook
	mutation *RepoPermissionMutation
}

// Where appends a list predicates to the RepoPermissionUpdate builder.
func (rpu *RepoPermissionUpdate) Where(ps ...predicate.RepoPermission) *RepoPermissionUpdate {
	rpu.mutation.Where(ps...)
	return rpu
}

// SetRepoPattern sets the "repo_pattern" field.
func (rpu *RepoPermissionUpdate) SetRepoPattern(s string) *RepoPermissionUpdate {
	rpu.mutation.SetRepoPattern(s)
	return rpu
}

// SetNillableRepoPattern sets the "repo_pattern" field if the given value is not nil.
func (rpu *RepoPermissionUpdate) SetNillableRepoPattern(s *string) *RepoPermissionUpdate {
	if s != nil {
		rpu.SetRepoPattern(*s)
	}
	return rpu
}

// SetUserID sets the "user" edge to the User entity by ID.
func (rpu *RepoPermissionUpdate) SetUserID(id int) *RepoPermissionUpdate {
	rpu.mutation.SetUserID(id)
	return rpu
}

// SetUser sets the "user" edge to the User entity.
func (rpu *RepoPermissionUpdate) SetUser(u *User) *RepoPermissionUpdate {
	return rpu.SetUserID(u.ID)
}

// Mutation returns the RepoPermissionMutation object of the builder.
func (rpu *RepoPermissionUpdate) Mutation() *RepoPermissionMutation {
	return rpu.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (rpu *RepoPermissionUpdate) ClearUser() *RepoPermissionUpdate {
	rpu.mutation.ClearUser()
	return rpu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (rpu *RepoPermissionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, rpu.sqlSave, rpu.mutation, rpu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (rpu *RepoPermissionUpdate) SaveX(ctx context.Context) int {
	affected, err := rpu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (rpu *RepoPermissionUpdate) Exec(ctx context.Context) error {
	_, err := rpu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rpu *RepoPermissionUpdate) ExecX(ctx context.Context) {
	if err := rpu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rpu *RepoPermissionUpdate) check() error {
	if v, ok := rpu.mutation.RepoPattern(); ok {
		if err := repopermission.RepoPatternValidator(v); err != nil {
			return &ValidationError{Name: "repo_pattern", err: fmt.Errorf(`ent: validator failed for field "RepoPermission.repo_pattern": %w`, err)}
		}
	}
	if rpu.mutation.UserCleared() && len(rpu.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RepoPermission.user"`)
	}
	return nil
}

func (rpu *RepoPermissionUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := rpu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(repopermission.Table, repopermission.Columns, sqlgraph.NewFieldSpec(repopermission.FieldID, field.TypeInt))
	if ps := rpu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := rpu.mutation.RepoPattern(); ok {
		_spec.SetField(repopermission.FieldRepoPattern, field.TypeString, value)
	}
	if rpu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   repopermission.UserTable,
			Columns: []string{repopermission.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := rpu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   repopermission.UserTable,
			Columns: []string{repopermission.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, rpu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{repopermission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	rpu.mutation.done = true
	return n, nil
}

// RepoPermissionUpdateOne is the builder for updating a single RepoPermission entity.
type RepoPermissionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RepoPermissionMutation
}

// SetRepoPattern sets the "repo_pattern" field.
func (rpuo *RepoPermissionUpdateOne) SetRepoPattern(s string) *RepoPermissionUpdateOne {
	rpuo.mutation.SetRepoPattern(s)
	return rpuo
}

// SetNillableRepoPattern sets the "repo_pattern" field if the given value is not nil.
func (rpuo *RepoPermissionUpdateOne) SetNillableRepoPattern(s *string) *RepoPermissionUpdateOne {
	if s != nil {
		rpuo.SetRepoPattern(*s)
	}
	return rpuo
}

// SetUserID sets the "user" edge to the User entity by ID.
func (rpuo *RepoPermissionUpdateOne) SetUserID(id int) *RepoPermissionUpdateOne {
	rpuo.mutation.SetUserID(id)
	return rpuo
}

// SetUser sets the "user" edge to the User entity.
func (rpuo *RepoPermissionUpdateOne) SetUser(u *User) *RepoPermissionUpdateOne {
	return rpuo.SetUserID(u.ID)
}

// Mutation returns the RepoPermissionMutation object of the builder.
func (rpuo *RepoPermissionUpdateOne) Mutation() *RepoPermissionMutation {
	return rpuo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (rpuo *RepoPermissionUpdateOne) ClearUser() *RepoPermissionUpdateOne {
	rpuo.mutation.ClearUser()
	return rpuo
}

// Where appends a list predicates to the RepoPermissionUpdate builder.
func (rpuo *RepoPermissionUpdateOne) Where(ps ...predicate.RepoPermission) *RepoPermissionUpdateOne {
	rpuo.mutation.Where(ps...)
	return rpuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (rpuo *RepoPermissionUpdateOne) Select(field string, fields ...string) *RepoPermissionUpdateOne {
	rpuo.fields = append([]string{field}, fields...)
	return rpuo
}

// Save executes the query and returns the updated RepoPermission entity.
func (rpuo *RepoPermissionUpdateOne) Save(ctx context.Context) (*RepoPermission, error) {
	return withHooks(ctx, rpuo.sqlSave, rpuo.mutation, rpuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (rpuo *RepoPermissionUpdateOne) SaveX(ctx context.Context) *RepoPermission {
	node, err := rpuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (rpuo *RepoPermissionUpdateOne) Exec(ctx context.Context) error {
	_, err := rpuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rpuo *RepoPermissionUpdateOne) ExecX(ctx context.Context) {
	if err := rpuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rpuo *RepoPermissionUpdateOne) check() error {
	if v, ok := rpuo.mutation.RepoPattern(); ok {
		if err := repopermission.RepoPatternValidator(v); err != nil {
			return &ValidationError{Name: "repo_pattern", err: fmt.Errorf(`ent: validator failed for field "RepoPermission.repo_pattern": %w`, err)}
		}
	}
	if rpuo.mutation.UserCleared() && len(rpuo.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RepoPermission.user"`)
	}
	return nil
}

func (rpuo *RepoPermissionUpdateOne) sqlSave(ctx context.Context) (_node *RepoPermission, err error) {
	if err := rpuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(repopermission.Table, repopermission.Columns, sqlgraph.NewFieldSpec(repopermission.FieldID, field.TypeInt))
	id, ok := rpuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RepoPermission.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := rpuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, repopermission.FieldID)
		for _, f := range fields {
			if !repopermission.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != repopermission.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := rpuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := rpuo.mutation.RepoPattern(); ok {
		_spec.SetField(repopermission.FieldRepoPattern, field.TypeString, value)
	}
	if rpuo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   repopermission.UserTable,
			Columns: []string{repopermission.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := rpuo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   repopermission.UserTable,
			Columns: []string{repopermission.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &RepoPermission{config: rpuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, rpuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{repopermission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	rpuo.mutation.done = true
	return _node, nil
}
