// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/internal/data/ent/predicate"
	"api/internal/data/ent/repopermission"
	"api/internal/data/ent/user"
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RepoPermissionQuery is the builder for querying RepoPermission entities.
type RepoPermissionQuery struct {
	config
	ctx        *QueryContext
	order      []repopermission.OrderOption
	inters     []Interceptor
	predicates []predicate.RepoPermission
	withUser   *UserQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RepoPermissionQuery builder.
func (rpq *RepoPermissionQuery) Where(ps ...predicate.RepoPermission) *RepoPermissionQuery {
	rpq.predicates = append(rpq.predicates, ps...)
	return rpq
}

// Limit the number of records to be returned by this query.
func (rpq *RepoPermissionQuery) Limit(limit int) *RepoPermissionQuery {
	rpq.ctx.Limit = &limit
	return rpq
}

// Offset to start from.
func (rpq *RepoPermissionQuery) Offset(offset int) *RepoPermissionQuery {
	rpq.ctx.Offset = &offset
	return rpq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (rpq *RepoPermissionQuery) Unique(unique bool) *RepoPermissionQuery {
	rpq.ctx.Unique = &unique
	return rpq
}

// Order specifies how the records should be ordered.
func (rpq *RepoPermissionQuery) Order(o ...repopermission.OrderOption) *RepoPermissionQuery {
	rpq.order = append(rpq.order, o...)
	return rpq
}

// QueryUser chains the current query on the "user" edge.
func (rpq *RepoPermissionQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: rpq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := rpq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := rpq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(repopermission.Table, repopermission.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, repopermission.UserTable, repopermission.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(rpq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first RepoPermission entity from the query.
// Returns a *NotFoundError when no RepoPermission was found.
func (rpq *RepoPermissionQuery) First(ctx context.Context) (*RepoPermission, error) {
	nodes, err := rpq.Limit(1).All(setContextOp(ctx, rpq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{repopermission.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (rpq *RepoPermissionQuery) FirstX(ctx context.Context) *RepoPermission {
	node, err := rpq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first RepoPermission ID from the query.
// Returns a *NotFoundError when no RepoPermission ID was found.
func (rpq *RepoPermissionQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rpq.Limit(1).IDs(setContextOp(ctx, rpq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{repopermission.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (rpq *RepoPermissionQuery) FirstIDX(ctx context.Context) int {
	id, err := rpq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single RepoPermission entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one RepoPermission entity is found.
// Returns a *NotFoundError when no RepoPermission entities are found.
func (rpq *RepoPermissionQuery) Only(ctx context.Context) (*RepoPermission, error) {
	nodes, err := rpq.Limit(2).All(setContextOp(ctx, rpq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{repopermission.Label}
	default:
		return nil, &NotSingularError{repopermission.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (rpq *RepoPermissionQuery) OnlyX(ctx context.Context) *RepoPermission {
	node, err := rpq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only RepoPermission ID in the query.
// Returns a *NotSingularError when more than one RepoPermission ID is found.
// Returns a *NotFoundError when no entities are found.
func (rpq *RepoPermissionQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rpq.Limit(2).IDs(setContextOp(ctx, rpq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{repopermission.Label}
	default:
		err = &NotSingularError{repopermission.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (rpq *RepoPermissionQuery) OnlyIDX(ctx context.Context) int {
	id, err := rpq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of RepoPermissions.
func (rpq *RepoPermissionQuery) All(ctx context.Context) ([]*RepoPermission, error) {
	ctx = setContextOp(ctx, rpq.ctx, ent.OpQueryAll)
	if err := rpq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*RepoPermission, *RepoPermissionQuery]()
	return withInterceptors[[]*RepoPermission](ctx, rpq, qr, rpq.inters)
}

// AllX is like All, but panics if an error occurs.
func (rpq *RepoPermissionQuery) AllX(ctx context.Context) []*RepoPermission {
	nodes, err := rpq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of RepoPermission IDs.
func (rpq *RepoPermissionQuery) IDs(ctx context.Context) (ids []int, err error) {
	if rpq.ctx.Unique == nil && rpq.path != nil {
		rpq.Unique(true)
	}
	ctx = setContextOp(ctx, rpq.ctx, ent.OpQueryIDs)
	if err = rpq.Select(repopermission.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (rpq *RepoPermissionQuery) IDsX(ctx context.Context) []int {
	ids, err := rpq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (rpq *RepoPermissionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, rpq.ctx, ent.OpQueryCount)
	if err := rpq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, rpq, querierCount[*RepoPermissionQuery](), rpq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (rpq *RepoPermissionQuery) CountX(ctx context.Context) int {
	count, err := rpq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (rpq *RepoPermissionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, rpq.ctx, ent.OpQueryExist)
	switch _, err := rpq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (rpq *RepoPermissionQuery) ExistX(ctx context.Context) bool {
	exist, err := rpq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RepoPermissionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (rpq *RepoPermissionQuery) Clone() *RepoPermissionQuery {
	if rpq == nil {
		return nil
	}
	return &RepoPermissionQuery{
		config:     rpq.config,
		ctx:        rpq.ctx.Clone(),
		order:      append([]repopermission.OrderOption{}, rpq.order...),
		inters:     append([]Interceptor{}, rpq.inters...),
		predicates: append([]predicate.RepoPermission{}, rpq.predicates...),
		withUser:   rpq.withUser.Clone(),
		// clone intermediate query.
		sql:  rpq.sql.Clone(),
		path: rpq.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (rpq *RepoPermissionQuery) WithUser(opts ...func(*UserQuery)) *RepoPermissionQuery {
	query := (&UserClient{config: rpq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	rpq.withUser = query
	return rpq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		RepoPattern string `json:"repo_pattern,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.RepoPermission.Query().
//		GroupBy(repopermission.FieldRepoPattern).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (rpq *RepoPermissionQuery) GroupBy(field string, fields ...string) *RepoPermissionGroupBy {
	rpq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &RepoPermissionGroupBy{build: rpq}
	grbuild.flds = &rpq.ctx.Fields
	grbuild.label = repopermission.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		RepoPattern string `json:"repo_pattern,omitempty"`
//	}
//
//	client.RepoPermission.Query().
//		Select(repopermission.FieldRepoPattern).
//		Scan(ctx, &v)
func (rpq *RepoPermissionQuery) Select(fields ...string) *RepoPermissionSelect {
	rpq.ctx.Fields = append(rpq.ctx.Fields, fields...)
	sbuild := &RepoPermissionSelect{RepoPermissionQuery: rpq}
	sbuild.label = repopermission.Label
	sbuild.flds, sbuild.scan = &rpq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a RepoPermissionSelect configured with the given aggregations.
func (rpq *RepoPermissionQuery) Aggregate(fns ...AggregateFunc) *RepoPermissionSelect {
	return rpq.Select().Aggregate(fns...)
}

func (rpq *RepoPermissionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range rpq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, rpq); err != nil {
				return err
			}
		}
	}
	for _, f := range rpq.ctx.Fields {
		if !repopermission.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if rpq.path != nil {
		prev, err := rpq.path(ctx)
		if err != nil {
			return err
		}
		rpq.sql = prev
	}
	return nil
}

func (rpq *RepoPermissionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*RepoPermission, error) {
	var (
		nodes       = []*RepoPermission{}
		withFKs     = rpq.withFKs
		_spec       = rpq.querySpec()
		loadedTypes = [1]bool{
			rpq.withUser != nil,
		}
	)
	if rpq.withUser != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, repopermission.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*RepoPermission).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &RepoPermission{config: rpq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, rpq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := rpq.withUser; query != nil {
		if err := rpq.loadUser(ctx, query, nodes, nil,
			func(n *RepoPermission, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (rpq *RepoPermissionQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*RepoPermission, init func(*RepoPermission), assign func(*RepoPermission, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*RepoPermission)
	for i := range nodes {
		if nodes[i].user_permissions == nil {
			continue
		}
		fk := *nodes[i].user_permissions
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_permissions" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (rpq *RepoPermissionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := rpq.querySpec()
	_spec.Node.Columns = rpq.ctx.Fields
	if len(rpq.ctx.Fields) > 0 {
		_spec.Unique = rpq.ctx.Unique != nil && *rpq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, rpq.driver, _spec)
}

func (rpq *RepoPermissionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(repopermission.Table, repopermission.Columns, sqlgraph.NewFieldSpec(repopermission.FieldID, field.TypeInt))
	_spec.From = rpq.sql
	if unique := rpq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if rpq.path != nil {
		_spec.Unique = true
	}
	if fields := rpq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, repopermission.FieldID)
		for i := range fields {
			if fields[i] != repopermission.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := rpq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := rpq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := rpq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := rpq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (rpq *RepoPermissionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(rpq.driver.Dialect())
	t1 := builder.Table(repopermission.Table)
	columns := rpq.ctx.Fields
	if len(columns) == 0 {
		columns = repopermission.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if rpq.sql != nil {
		selector = rpq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if rpq.ctx.Unique != nil && *rpq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range rpq.predicates {
		p(selector)
	}
	for _, p := range rpq.order {
		p(selector)
	}
	if offset := rpq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := rpq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// RepoPermissionGroupBy is the group-by builder for RepoPermission entities.
type RepoPermissionGroupBy struct {
	selector
	build *RepoPermissionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rpgb *RepoPermissionGroupBy) Aggregate(fns ...AggregateFunc) *RepoPermissionGroupBy {
	rpgb.fns = append(rpgb.fns, fns...)
	return rpgb
}

// Scan applies the selector query and scans the result into the given value.
func (rpgb *RepoPermissionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rpgb.build.ctx, ent.OpQueryGroupBy)
	if err := rpgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RepoPermissionQuery, *RepoPermissionGroupBy](ctx, rpgb.build, rpgb, rpgb.build.inters, v)
}

func (rpgb *RepoPermissionGroupBy) sqlScan(ctx context.Context, root *RepoPermissionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(rpgb.fns))
	for _, fn := range rpgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*rpgb.flds)+len(rpgb.fns))
		for _, f := range *rpgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*rpgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rpgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// RepoPermissionSelect is the builder for selecting fields of RepoPermission entities.
type RepoPermissionSelect struct {
	*RepoPermissionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (rps *RepoPermissionSelect) Aggregate(fns ...AggregateFunc) *RepoPermissionSelect {
	rps.fns = append(rps.fns, fns...)
	return rps
}

// Scan applies the selector query and scans the result into the given value.
func (rps *RepoPermissionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rps.ctx, ent.OpQuerySelect)
	if err := rps.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RepoPermissionQuery, *RepoPermissionSelect](ctx, rps.RepoPermissionQuery, rps, rps.inters, v)
}

func (rps *RepoPermissionSelect) sqlScan(ctx context.Context, root *RepoPermissionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(rps.fns))
	for _, fn := range rps.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*rps.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
