// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/internal/data/ent/predicate"
	"api/internal/data/ent/repometa"
	"api/internal/data/ent/schema"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// RepoMetaUpdate is the builder for updating RepoMeta entities.
type RepoMetaUpdate struct {
	config
	hooks    []Hook
	mutation *RepoMetaMutation
}

// Where appends a list predicates to the RepoMetaUpdate builder.
func (rmu *RepoMetaUpdate) Where(ps ...predicate.RepoMeta) *RepoMetaUpdate {
	rmu.mutation.Where(ps...)
	return rmu
}

// SetLatestTag sets the "latest_tag" field.
func (rmu *RepoMetaUpdate) SetLatestTag(s string) *RepoMetaUpdate {
	rmu.mutation.SetLatestTag(s)
	return rmu
}

// SetNillableLatestTag sets the "latest_tag" field if the given value is not nil.
func (rmu *RepoMetaUpdate) SetNillableLatestTag(s *string) *RepoMetaUpdate {
	if s != nil {
		rmu.SetLatestTag(*s)
	}
	return rmu
}

// ClearLatestTag clears the value of the "latest_tag" field.
func (rmu *RepoMetaUpdate) ClearLatestTag() *RepoMetaUpdate {
	rmu.mutation.ClearLatestTag()
	return rmu
}

// SetTagCount sets the "tag_count" field.
func (rmu *RepoMetaUpdate) SetTagCount(i int) *RepoMetaUpdate {
	rmu.mutation.ResetTagCount()
	rmu.mutation.SetTagCount(i)
	return rmu
}

// SetNillableTagCount sets the "tag_count" field if the given value is not nil.
func (rmu *RepoMetaUpdate) SetNillableTagCount(i *int) *RepoMetaUpdate {
	if i != nil {
		rmu.SetTagCount(*i)
	}
	return rmu
}

// AddTagCount adds i to the "tag_count" field.
func (rmu *RepoMetaUpdate) AddTagCount(i int) *RepoMetaUpdate {
	rmu.mutation.AddTagCount(i)
	return rmu
}

// SetSize sets the "size" field.
func (rmu *RepoMetaUpdate) SetSize(i int64) *RepoMetaUpdate {
	rmu.mutation.ResetSize()
	rmu.mutation.SetSize(i)
	return rmu
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (rmu *RepoMetaUpdate) SetNillableSize(i *int64) *RepoMetaUpdate {
	if i != nil {
		rmu.SetSize(*i)
	}
	return rmu
}

// AddSize adds i to the "size" field.
func (rmu *RepoMetaUpdate) AddSize(i int64) *RepoMetaUpdate {
	rmu.mutation.AddSize(i)
	return rmu
}

// SetCreated sets the "created" field.
func (rmu *RepoMetaUpdate) SetCreated(s string) *RepoMetaUpdate {
	rmu.mutation.SetCreated(s)
	return rmu
}

// SetNillableCreated sets the "created" field if the given value is not nil.
func (rmu *RepoMetaUpdate) SetNillableCreated(s *string) *RepoMetaUpdate {
	if s != nil {
		rmu.SetCreated(*s)
	}
	return rmu
}

// ClearCreated clears the value of the "created" field.
func (rmu *RepoMetaUpdate) ClearCreated() *RepoMetaUpdate {
	rmu.mutation.ClearCreated()
	return rmu
}

// SetPlatforms sets the "platforms" field.
func (rmu *RepoMetaUpdate) SetPlatforms(si []schema.PlatformInfo) *RepoMetaUpdate {
	rmu.mutation.SetPlatforms(si)
	return rmu
}

// AppendPlatforms appends si to the "platforms" field.
func (rmu *RepoMetaUpdate) AppendPlatforms(si []schema.PlatformInfo) *RepoMetaUpdate {
	rmu.mutation.AppendPlatforms(si)
	return rmu
}

// ClearPlatforms clears the value of the "platforms" field.
func (rmu *RepoMetaUpdate) ClearPlatforms() *RepoMetaUpdate {
	rmu.mutation.ClearPlatforms()
	return rmu
}

// SetPullCount sets the "pull_count" field.
func (rmu *RepoMetaUpdate) SetPullCount(i int64) *RepoMetaUpdate {
	rmu.mutation.ResetPullCount()
	rmu.mutation.SetPullCount(i)
	return rmu
}

// SetNillablePullCount sets the "pull_count" field if the given value is not nil.
func (rmu *RepoMetaUpdate) SetNillablePullCount(i *int64) *RepoMetaUpdate {
	if i != nil {
		rmu.SetPullCount(*i)
	}
	return rmu
}

// AddPullCount adds i to the "pull_count" field.
func (rmu *RepoMetaUpdate) AddPullCount(i int64) *RepoMetaUpdate {
	rmu.mutation.AddPullCount(i)
	return rmu
}

// SetLastPulledAt sets the "last_pulled_at" field.
func (rmu *RepoMetaUpdate) SetLastPulledAt(t time.Time) *RepoMetaUpdate {
	rmu.mutation.SetLastPulledAt(t)
	return rmu
}

// SetNillableLastPulledAt sets the "last_pulled_at" field if the given value is not nil.
func (rmu *RepoMetaUpdate) SetNillableLastPulledAt(t *time.Time) *RepoMetaUpdate {
	if t != nil {
		rmu.SetLastPulledAt(*t)
	}
	return rmu
}

// ClearLastPulledAt clears the value of the "last_pulled_at" field.
func (rmu *RepoMetaUpdate) ClearLastPulledAt() *RepoMetaUpdate {
	rmu.mutation.ClearLastPulledAt()
	return rmu
}

// SetRefreshedAt sets the "refreshed_at" field.
func (rmu *RepoMetaUpdate) SetRefreshedAt(t time.Time) *RepoMetaUpdate {
	rmu.mutation.SetRefreshedAt(t)
	return rmu
}

// Mutation returns the RepoMetaMutation object of the builder.
func (rmu *RepoMetaUpdate) Mutation() *RepoMetaMutation {
	return rmu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (rmu *RepoMetaUpdate) Save(ctx context.Context) (int, error) {
	rmu.defaults()
	return withHooks(ctx, rmu.sqlSave, rmu.mutation, rmu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (rmu *RepoMetaUpdate) SaveX(ctx context.Context) int {
	affected, err := rmu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (rmu *RepoMetaUpdate) Exec(ctx context.Context) error {
	_, err := rmu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rmu *RepoMetaUpdate) ExecX(ctx context.Context) {
	if err := rmu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (rmu *RepoMetaUpdate) defaults() {
	if _, ok := rmu.mutation.RefreshedAt(); !ok {
		v := repometa.UpdateDefaultRefreshedAt()
		rmu.mutation.SetRefreshedAt(v)
	}
}

func (rmu *RepoMetaUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(repometa.Table, repometa.Columns, sqlgraph.NewFieldSpec(repometa.FieldID, field.TypeInt))
	if ps := rmu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := rmu.mutation.LatestTag(); ok {
		_spec.SetField(repometa.FieldLatestTag, field.TypeString, value)
	}
	if rmu.mutation.LatestTagCleared() {
		_spec.ClearField(repometa.FieldLatestTag, field.TypeString)
	}
	if value, ok := rmu.mutation.TagCount(); ok {
		_spec.SetField(repometa.FieldTagCount, field.TypeInt, value)
	}
	if value, ok := rmu.mutation.AddedTagCount(); ok {
		_spec.AddField(repometa.FieldTagCount, field.TypeInt, value)
	}
	if value, ok := rmu.mutation.Size(); ok {
		_spec.SetField(repometa.FieldSize, field.TypeInt64, value)
	}
	if value, ok := rmu.mutation.AddedSize(); ok {
		_spec.AddField(repometa.FieldSize, field.TypeInt64, value)
	}
	if value, ok := rmu.mutation.Created(); ok {
		_spec.SetField(repometa.FieldCreated, field.TypeString, value)
	}
	if rmu.mutation.CreatedCleared() {
		_spec.ClearField(repometa.FieldCreated, field.TypeString)
	}
	if value, ok := rmu.mutation.Platforms(); ok {
		_spec.SetField(repometa.FieldPlatforms, field.TypeJSON, value)
	}
	if value, ok := rmu.mutation.AppendedPlatforms(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, repometa.FieldPlatforms, value)
		})
	}
	if rmu.mutation.PlatformsCleared() {
		_spec.ClearField(repometa.FieldPlatforms, field.TypeJSON)
	}
	if value, ok := rmu.mutation.PullCount(); ok {
		_spec.SetField(repometa.FieldPullCount, field.TypeInt64, value)
	}
	if value, ok := rmu.mutation.AddedPullCount(); ok {
		_spec.AddField(repometa.FieldPullCount, field.TypeInt64, value)
	}
	if value, ok := rmu.mutation.LastPulledAt(); ok {
		_spec.SetField(repometa.FieldLastPulledAt, field.TypeTime, value)
	}
	if rmu.mutation.LastPulledAtCleared() {
		_spec.ClearField(repometa.FieldLastPulledAt, field.TypeTime)
	}
	if value, ok := rmu.mutation.RefreshedAt(); ok {
		_spec.SetField(repometa.FieldRefreshedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, rmu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{repometa.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	rmu.mutation.done = true
	return n, nil
}

// RepoMetaUpdateOne is the builder for updating a single RepoMeta entity.
type RepoMetaUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RepoMetaMutation
}

// SetLatestTag sets the "latest_tag" field.
func (rmuo *RepoMetaUpdateOne) SetLatestTag(s string) *RepoMetaUpdateOne {
	rmuo.mutation.SetLatestTag(s)
	return rmuo
}

// SetNillableLatestTag sets the "latest_tag" field if the given value is not nil.
func (rmuo *RepoMetaUpdateOne) SetNillableLatestTag(s *string) *RepoMetaUpdateOne {
	if s != nil {
		rmuo.SetLatestTag(*s)
	}
	return rmuo
}

// ClearLatestTag clears the value of the "latest_tag" field.
func (rmuo *RepoMetaUpdateOne) ClearLatestTag() *RepoMetaUpdateOne {
	rmuo.mutation.ClearLatestTag()
	return rmuo
}

// SetTagCount sets the "tag_count" field.
func (rmuo *RepoMetaUpdateOne) SetTagCount(i int) *RepoMetaUpdateOne {
	rmuo.mutation.ResetTagCount()
	rmuo.mutation.SetTagCount(i)
	return rmuo
}

// SetNillableTagCount sets the "tag_count" field if the given value is not nil.
func (rmuo *RepoMetaUpdateOne) SetNillableTagCount(i *int) *RepoMetaUpdateOne {
	if i != nil {
		rmuo.SetTagCount(*i)
	}
	return rmuo
}

// AddTagCount adds i to the "tag_count" field.
func (rmuo *RepoMetaUpdateOne) AddTagCount(i int) *RepoMetaUpdateOne {
	rmuo.mutation.AddTagCount(i)
	return rmuo
}

// SetSize sets the "size" field.
func (rmuo *RepoMetaUpdateOne) SetSize(i int64) *RepoMetaUpdateOne {
	rmuo.mutation.ResetSize()
	rmuo.mutation.SetSize(i)
	return rmuo
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (rmuo *RepoMetaUpdateOne) SetNillableSize(i *int64) *RepoMetaUpdateOne {
	if i != nil {
		rmuo.SetSize(*i)
	}
	return rmuo
}

// AddSize adds i to the "size" field.
func (rmuo *RepoMetaUpdateOne) AddSize(i int64) *RepoMetaUpdateOne {
	rmuo.mutation.AddSize(i)
	return rmuo
}

// SetCreated sets the "created" field.
func (rmuo *RepoMetaUpdateOne) SetCreated(s string) *RepoMetaUpdateOne {
	rmuo.mutation.SetCreated(s)
	return rmuo
}

// SetNillableCreated sets the "created" field if the given value is not nil.
func (rmuo *RepoMetaUpdateOne) SetNillableCreated(s *string) *RepoMetaUpdateOne {
	if s != nil {
		rmuo.SetCreated(*s)
	}
	return rmuo
}

// ClearCreated clears the value of the "created" field.
func (rmuo *RepoMetaUpdateOne) ClearCreated() *RepoMetaUpdateOne {
	rmuo.mutation.ClearCreated()
	return rmuo
}

// SetPlatforms sets the "platforms" field.
func (rmuo *RepoMetaUpdateOne) SetPlatforms(si []schema.PlatformInfo) *RepoMetaUpdateOne {
	rmuo.mutation.SetPlatforms(si)
	return rmuo
}

// AppendPlatforms appends si to the "platforms" field.
func (rmuo *RepoMetaUpdateOne) AppendPlatforms(si []schema.PlatformInfo) *RepoMetaUpdateOne {
	rmuo.mutation.AppendPlatforms(si)
	return rmuo
}

// ClearPlatforms clears the value of the "platforms" field.
func (rmuo *RepoMetaUpdateOne) ClearPlatforms() *RepoMetaUpdateOne {
	rmuo.mutation.ClearPlatforms()
	return rmuo
}

// SetPullCount sets the "pull_count" field.
func (rmuo *RepoMetaUpdateOne) SetPullCount(i int64) *RepoMetaUpdateOne {
	rmuo.mutation.ResetPullCount()
	rmuo.mutation.SetPullCount(i)
	return rmuo
}

// SetNillablePullCount sets the "pull_count" field if the given value is not nil.
func (rmuo *RepoMetaUpdateOne) SetNillablePullCount(i *int64) *RepoMetaUpdateOne {
	if i != nil {
		rmuo.SetPullCount(*i)
	}
	return rmuo
}

// AddPullCount adds i to the "pull_count" field.
func (rmuo *RepoMetaUpdateOne) AddPullCount(i int64) *RepoMetaUpdateOne {
	rmuo.mutation.AddPullCount(i)
	return rmuo
}

// SetLastPulledAt sets the "last_pulled_at" field.
func (rmuo *RepoMetaUpdateOne) SetLastPulledAt(t time.Time) *RepoMetaUpdateOne {
	rmuo.mutation.SetLastPulledAt(t)
	return rmuo
}

// SetNillableLastPulledAt sets the "last_pulled_at" field if the given value is not nil.
func (rmuo *RepoMetaUpdateOne) SetNillableLastPulledAt(t *time.Time) *RepoMetaUpdateOne {
	if t != nil {
		rmuo.SetLastPulledAt(*t)
	}
	return rmuo
}

// ClearLastPulledAt clears the value of the "last_pulled_at" field.
func (rmuo *RepoMetaUpdateOne) ClearLastPulledAt() *RepoMetaUpdateOne {
	rmuo.mutation.ClearLastPulledAt()
	return rmuo
}

// SetRefreshedAt sets the "refreshed_at" field.
func (rmuo *RepoMetaUpdateOne) SetRefreshedAt(t time.Time) *RepoMetaUpdateOne {
	rmuo.mutation.SetRefreshedAt(t)
	return rmuo
}

// Mutation returns the RepoMetaMutation object of the builder.
func (rmuo *RepoMetaUpdateOne) Mutation() *RepoMetaMutation {
	return rmuo.mutation
}

// Where appends a list predicates to the RepoMetaUpdate builder.
func (rmuo *RepoMetaUpdateOne) Where(ps ...predicate.RepoMeta) *RepoMetaUpdateOne {
	rmuo.mutation.Where(ps...)
	return rmuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (rmuo *RepoMetaUpdateOne) Select(field string, fields ...string) *RepoMetaUpdateOne {
	rmuo.fields = append([]string{field}, fields...)
	return rmuo
}

// Save executes the query and returns the updated RepoMeta entity.
func (rmuo *RepoMetaUpdateOne) Save(ctx context.Context) (*RepoMeta, error) {
	rmuo.defaults()
	return withHooks(ctx, rmuo.sqlSave, rmuo.mutation, rmuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (rmuo *RepoMetaUpdateOne) SaveX(ctx context.Context) *RepoMeta {
	node, err := rmuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (rmuo *RepoMetaUpdateOne) Exec(ctx context.Context) error {
	_, err := rmuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rmuo *RepoMetaUpdateOne) ExecX(ctx context.Context) {
	if err := rmuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (rmuo *RepoMetaUpdateOne) defaults() {
	if _, ok := rmuo.mutation.RefreshedAt(); !ok {
		v := repometa.UpdateDefaultRefreshedAt()
		rmuo.mutation.SetRefreshedAt(v)
	}
}

func (rmuo *RepoMetaUpdateOne) sqlSave(ctx context.Context) (_node *RepoMeta, err error) {
	_spec := sqlgraph.NewUpdateSpec(repometa.Table, repometa.Columns, sqlgraph.NewFieldSpec(repometa.FieldID, field.TypeInt))
	id, ok := rmuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RepoMeta.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := rmuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, repometa.FieldID)
		for _, f := range fields {
			if !repometa.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != repometa.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := rmuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := rmuo.mutation.LatestTag(); ok {
		_spec.SetField(repometa.FieldLatestTag, field.TypeString, value)
	}
	if rmuo.mutation.LatestTagCleared() {
		_spec.ClearField(repometa.FieldLatestTag, field.TypeString)
	}
	if value, ok := rmuo.mutation.TagCount(); ok {
		_spec.SetField(repometa.FieldTagCount, field.TypeInt, value)
	}
	if value, ok := rmuo.mutation.AddedTagCount(); ok {
		_spec.AddField(repometa.FieldTagCount, field.TypeInt, value)
	}
	if value, ok := rmuo.mutation.Size(); ok {
		_spec.SetField(repometa.FieldSize, field.TypeInt64, value)
	}
	if value, ok := rmuo.mutation.AddedSize(); ok {
		_spec.AddField(repometa.FieldSize, field.TypeInt64, value)
	}
	if value, ok := rmuo.mutation.Created(); ok {
		_spec.SetField(repometa.FieldCreated, field.TypeString, value)
	}
	if rmuo.mutation.CreatedCleared() {
		_spec.ClearField(repometa.FieldCreated, field.TypeString)
	}
	if value, ok := rmuo.mutation.Platforms(); ok {
		_spec.SetField(repometa.FieldPlatforms, field.TypeJSON, value)
	}
	if value, ok := rmuo.mutation.AppendedPlatforms(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, repometa.FieldPlatforms, value)
		})
	}
	if rmuo.mutation.PlatformsCleared() {
		_spec.ClearField(repometa.FieldPlatforms, field.TypeJSON)
	}
	if value, ok := rmuo.mutation.PullCount(); ok {
		_spec.SetField(repometa.FieldPullCount, field.TypeInt64, value)
	}
	if value, ok := rmuo.mutation.AddedPullCount(); ok {
		_spec.AddField(repometa.FieldPullCount, field.TypeInt64, value)
	}
	if value, ok := rmuo.mutation.LastPulledAt(); ok {
		_spec.SetField(repometa.FieldLastPulledAt, field.TypeTime, value)
	}
	if rmuo.mutation.LastPulledAtCleared() {
		_spec.ClearField(repometa.FieldLastPulledAt, field.TypeTime)
	}
	if value, ok := rmuo.mutation.RefreshedAt(); ok {
		_spec.SetField(repometa.FieldRefreshedAt, field.TypeTime, value)
	}
	_node = &RepoMeta{config: rmuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, rmuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{repometa.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	rmuo.mutation.done = true
	return _node, nil
}
