// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/internal/data/ent/repopermission"
	"api/internal/data/ent/user"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// RepoPermission is the model entity for the RepoPermission schema.
type RepoPermission struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// RepoPattern holds the value of the "repo_pattern" field.
	RepoPattern string `json:"repo_pattern,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RepoPermissionQuery when eager-loading is set.
	Edges            RepoPermissionEdges `json:"edges"`
	user_permissions *int
	selectValues     sql.SelectValues
}

// RepoPermissionEdges holds the relations/edges for other nodes in the graph.
type RepoPermissionEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RepoPermissionEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RepoPermission) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case repopermission.FieldID:
			values[i] = new(sql.NullInt64)
		case repopermission.FieldRepoPattern:
			values[i] = new(sql.NullString)
		case repopermission.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case repopermission.ForeignKeys[0]: // user_permissions
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RepoPermission fields.
func (rp *RepoPermission) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case repopermission.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			rp.ID = int(value.Int64)
		case repopermission.FieldRepoPattern:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field repo_pattern", values[i])
			} else if value.Valid {
				rp.RepoPattern = value.String
			}
		case repopermission.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				rp.CreatedAt = value.Time
			}
		case repopermission.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_permissions", value)
			} else if value.Valid {
				rp.user_permissions = new(int)
				*rp.user_permissions = int(value.Int64)
			}
		default:
			rp.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RepoPermission.
// This includes values selected through modifiers, order, etc.
func (rp *RepoPermission) Value(name string) (ent.Value, error) {
	return rp.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the RepoPermission entity.
func (rp *RepoPermission) QueryUser() *UserQuery {
	return NewRepoPermissionClient(rp.config).QueryUser(rp)
}

// Update returns a builder for updating this RepoPermission.
// Note that you need to call RepoPermission.Unwrap() before calling this method if this RepoPermission
// was returned from a transaction, and the transaction was committed or rolled back.
func (rp *RepoPermission) Update() *RepoPermissionUpdateOne {
	return NewRepoPermissionClient(rp.config).UpdateOne(rp)
}

// Unwrap unwraps the RepoPermission entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (rp *RepoPermission) Unwrap() *RepoPermission {
	_tx, ok := rp.config.driver.(*txDriver)
	if !ok {
		panic("ent: RepoPermission is not a transactional entity")
	}
	rp.config.driver = _tx.drv
	return rp
}

// String implements the fmt.Stringer.
func (rp *RepoPermission) String() string {
	var builder strings.Builder
	builder.WriteString("RepoPermission(")
	builder.WriteString(fmt.Sprintf("id=%v, ", rp.ID))
	builder.WriteString("repo_pattern=")
	builder.WriteString(rp.RepoPattern)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(rp.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// RepoPermissions is a parsable slice of RepoPermission.
type RepoPermissions []*RepoPermission
