// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/internal/data/ent/repometa"
	"api/internal/data/ent/schema"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// RepoMeta is the model entity for the RepoMeta schema.
type RepoMeta struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Repo holds the value of the "repo" field.
	Repo string `json:"repo,omitempty"`
	// LatestTag holds the value of the "latest_tag" field.
	LatestTag string `json:"latest_tag,omitempty"`
	// TagCount holds the value of the "tag_count" field.
	TagCount int `json:"tag_count,omitempty"`
	// Size holds the value of the "size" field.
	Size int64 `json:"size,omitempty"`
	// Created holds the value of the "created" field.
	Created string `json:"created,omitempty"`
	// Platforms holds the value of the "platforms" field.
	Platforms []schema.PlatformInfo `json:"platforms,omitempty"`
	// PullCount holds the value of the "pull_count" field.
	PullCount int64 `json:"pull_count,omitempty"`
	// LastPulledAt holds the value of the "last_pulled_at" field.
	LastPulledAt *time.Time `json:"last_pulled_at,omitempty"`
	// RefreshedAt holds the value of the "refreshed_at" field.
	RefreshedAt  time.Time `json:"refreshed_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RepoMeta) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case repometa.FieldPlatforms:
			values[i] = new([]byte)
		case repometa.FieldID, repometa.FieldTagCount, repometa.FieldSize, repometa.FieldPullCount:
			values[i] = new(sql.NullInt64)
		case repometa.FieldRepo, repometa.FieldLatestTag, repometa.FieldCreated:
			values[i] = new(sql.NullString)
		case repometa.FieldLastPulledAt, repometa.FieldRefreshedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RepoMeta fields.
func (rm *RepoMeta) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case repometa.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			rm.ID = int(value.Int64)
		case repometa.FieldRepo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field repo", values[i])
			} else if value.Valid {
				rm.Repo = value.String
			}
		case repometa.FieldLatestTag:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field latest_tag", values[i])
			} else if value.Valid {
				rm.LatestTag = value.String
			}
		case repometa.FieldTagCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tag_count", values[i])
			} else if value.Valid {
				rm.TagCount = int(value.Int64)
			}
		case repometa.FieldSize:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field size", values[i])
			} else if value.Valid {
				rm.Size = value.Int64
			}
		case repometa.FieldCreated:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created", values[i])
			} else if value.Valid {
				rm.Created = value.String
			}
		case repometa.FieldPlatforms:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field platforms", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &rm.Platforms); err != nil {
					return fmt.Errorf("unmarshal field platforms: %w", err)
				}
			}
		case repometa.FieldPullCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field pull_count", values[i])
			} else if value.Valid {
				rm.PullCount = value.Int64
			}
		case repometa.FieldLastPulledAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_pulled_at", values[i])
			} else if value.Valid {
				rm.LastPulledAt = new(time.Time)
				*rm.LastPulledAt = value.Time
			}
		case repometa.FieldRefreshedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field refreshed_at", values[i])
			} else if value.Valid {
				rm.RefreshedAt = value.Time
			}
		default:
			rm.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RepoMeta.
// This includes values selected through modifiers, order, etc.
func (rm *RepoMeta) Value(name string) (ent.Value, error) {
	return rm.selectValues.Get(name)
}

// Update returns a builder for updating this RepoMeta.
// Note that you need to call RepoMeta.Unwrap() before calling this method if this RepoMeta
// was returned from a transaction, and the transaction was committed or rolled back.
func (rm *RepoMeta) Update() *RepoMetaUpdateOne {
	return NewRepoMetaClient(rm.config).UpdateOne(rm)
}

// Unwrap unwraps the RepoMeta entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (rm *RepoMeta) Unwrap() *RepoMeta {
	_tx, ok := rm.config.driver.(*txDriver)
	if !ok {
		panic("ent: RepoMeta is not a transactional entity")
	}
	rm.config.driver = _tx.drv
	return rm
}

// String implements the fmt.Stringer.
func (rm *RepoMeta) String() string {
	var builder strings.Builder
	builder.WriteString("RepoMeta(")
	builder.WriteString(fmt.Sprintf("id=%v, ", rm.ID))
	builder.WriteString("repo=")
	builder.WriteString(rm.Repo)
	builder.WriteString(", ")
	builder.WriteString("latest_tag=")
	builder.WriteString(rm.LatestTag)
	builder.WriteString(", ")
	builder.WriteString("tag_count=")
	builder.WriteString(fmt.Sprintf("%v", rm.TagCount))
	builder.WriteString(", ")
	builder.WriteString("size=")
	builder.WriteString(fmt.Sprintf("%v", rm.Size))
	builder.WriteString(", ")
	builder.WriteString("created=")
	builder.WriteString(rm.Created)
	builder.WriteString(", ")
	builder.WriteString("platforms=")
	builder.WriteString(fmt.Sprintf("%v", rm.Platforms))
	builder.WriteString(", ")
	builder.WriteString("pull_count=")
	builder.WriteString(fmt.Sprintf("%v", rm.PullCount))
	builder.WriteString(", ")
	if v := rm.LastPulledAt; v != nil {
		builder.WriteString("last_pulled_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("refreshed_at=")
	builder.WriteString(rm.RefreshedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// RepoMetaSlice is a parsable slice of RepoMeta.
type RepoMetaSlice []*RepoMeta
