// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/internal/data/ent/repometa"
	"api/internal/data/ent/schema"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RepoMetaCreate is the builder for creating a RepoMeta entity.
type RepoMetaCreate struct {
	config
	mutation *RepoMetaMutation
	hooks    []Hook
}

// SetRepo sets the "repo" field.
func (rmc *RepoMetaCreate) SetRepo(s string) *RepoMetaCreate {
	rmc.mutation.SetRepo(s)
	return rmc
}

// SetLatestTag sets the "latest_tag" field.
func (rmc *RepoMetaCreate) SetLatestTag(s string) *RepoMetaCreate {
	rmc.mutation.SetLatestTag(s)
	return rmc
}

// SetNillableLatestTag sets the "latest_tag" field if the given value is not nil.
func (rmc *RepoMetaCreate) SetNillableLatestTag(s *string) *RepoMetaCreate {
	if s != nil {
		rmc.SetLatestTag(*s)
	}
	return rmc
}

// SetTagCount sets the "tag_count" field.
func (rmc *RepoMetaCreate) SetTagCount(i int) *RepoMetaCreate {
	rmc.mutation.SetTagCount(i)
	return rmc
}

// SetNillableTagCount sets the "tag_count" field if the given value is not nil.
func (rmc *RepoMetaCreate) SetNillableTagCount(i *int) *RepoMetaCreate {
	if i != nil {
		rmc.SetTagCount(*i)
	}
	return rmc
}

// SetSize sets the "size" field.
func (rmc *RepoMetaCreate) SetSize(i int64) *RepoMetaCreate {
	rmc.mutation.SetSize(i)
	return rmc
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (rmc *RepoMetaCreate) SetNillableSize(i *int64) *RepoMetaCreate {
	if i != nil {
		rmc.SetSize(*i)
	}
	return rmc
}

// SetCreated sets the "created" field.
func (rmc *RepoMetaCreate) SetCreated(s string) *RepoMetaCreate {
	rmc.mutation.SetCreated(s)
	return rmc
}

// SetNillableCreated sets the "created" field if the given value is not nil.
func (rmc *RepoMetaCreate) SetNillableCreated(s *string) *RepoMetaCreate {
	if s != nil {
		rmc.SetCreated(*s)
	}
	return rmc
}

// SetPlatforms sets the "platforms" field.
func (rmc *RepoMetaCreate) SetPlatforms(si []schema.PlatformInfo) *RepoMetaCreate {
	rmc.mutation.SetPlatforms(si)
	return rmc
}

// SetPullCount sets the "pull_count" field.
func (rmc *RepoMetaCreate) SetPullCount(i int64) *RepoMetaCreate {
	rmc.mutation.SetPullCount(i)
	return rmc
}

// SetNillablePullCount sets the "pull_count" field if the given value is not nil.
func (rmc *RepoMetaCreate) SetNillablePullCount(i *int64) *RepoMetaCreate {
	if i != nil {
		rmc.SetPullCount(*i)
	}
	return rmc
}

// SetLastPulledAt sets the "last_pulled_at" field.
func (rmc *RepoMetaCreate) SetLastPulledAt(t time.Time) *RepoMetaCreate {
	rmc.mutation.SetLastPulledAt(t)
	return rmc
}

// SetNillableLastPulledAt sets the "last_pulled_at" field if the given value is not nil.
func (rmc *RepoMetaCreate) SetNillableLastPulledAt(t *time.Time) *RepoMetaCreate {
	if t != nil {
		rmc.SetLastPulledAt(*t)
	}
	return rmc
}

// SetRefreshedAt sets the "refreshed_at" field.
func (rmc *RepoMetaCreate) SetRefreshedAt(t time.Time) *RepoMetaCreate {
	rmc.mutation.SetRefreshedAt(t)
	return rmc
}

// SetNillableRefreshedAt sets the "refreshed_at" field if the given value is not nil.
func (rmc *RepoMetaCreate) SetNillableRefreshedAt(t *time.Time) *RepoMetaCreate {
	if t != nil {
		rmc.SetRefreshedAt(*t)
	}
	return rmc
}

// Mutation returns the RepoMetaMutation object of the builder.
func (rmc *RepoMetaCreate) Mutation() *RepoMetaMutation {
	return rmc.mutation
}

// Save creates the RepoMeta in the database.
func (rmc *RepoMetaCreate) Save(ctx context.Context) (*RepoMeta, error) {
	rmc.defaults()
	return withHooks(ctx, rmc.sqlSave, rmc.mutation, rmc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (rmc *RepoMetaCreate) SaveX(ctx context.Context) *RepoMeta {
	v, err := rmc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rmc *RepoMetaCreate) Exec(ctx context.Context) error {
	_, err := rmc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rmc *RepoMetaCreate) ExecX(ctx context.Context) {
	if err := rmc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (rmc *RepoMetaCreate) defaults() {
	if _, ok := rmc.mutation.TagCount(); !ok {
		v := repometa.DefaultTagCount
		rmc.mutation.SetTagCount(v)
	}
	if _, ok := rmc.mutation.Size(); !ok {
		v := repometa.DefaultSize
		rmc.mutation.SetSize(v)
	}
	if _, ok := rmc.mutation.PullCount(); !ok {
		v := repometa.DefaultPullCount
		rmc.mutation.SetPullCount(v)
	}
	if _, ok := rmc.mutation.RefreshedAt(); !ok {
		v := repometa.DefaultRefreshedAt()
		rmc.mutation.SetRefreshedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rmc *RepoMetaCreate) check() error {
	if _, ok := rmc.mutation.Repo(); !ok {
		return &ValidationError{Name: "repo", err: errors.New(`ent: missing required field "RepoMeta.repo"`)}
	}
	if v, ok := rmc.mutation.Repo(); ok {
		if err := repometa.RepoValidator(v); err != nil {
			return &ValidationError{Name: "repo", err: fmt.Errorf(`ent: validator failed for field "RepoMeta.repo": %w`, err)}
		}
	}
	if _, ok := rmc.mutation.TagCount(); !ok {
		return &ValidationError{Name: "tag_count", err: errors.New(`ent: missing required field "RepoMeta.tag_count"`)}
	}
	if _, ok := rmc.mutation.Size(); !ok {
		return &ValidationError{Name: "size", err: errors.New(`ent: missing required field "RepoMeta.size"`)}
	}
	if _, ok := rmc.mutation.PullCount(); !ok {
		return &ValidationError{Name: "pull_count", err: errors.New(`ent: missing required field "RepoMeta.pull_count"`)}
	}
	if _, ok := rmc.mutation.RefreshedAt(); !ok {
		return &ValidationError{Name: "refreshed_at", err: errors.New(`ent: missing required field "RepoMeta.refreshed_at"`)}
	}
	return nil
}

func (rmc *RepoMetaCreate) sqlSave(ctx context.Context) (*RepoMeta, error) {
	if err := rmc.check(); err != nil {
		return nil, err
	}
	_node, _spec := rmc.createSpec()
	if err := sqlgraph.CreateNode(ctx, rmc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	rmc.mutation.id = &_node.ID
	rmc.mutation.done = true
	return _node, nil
}

func (rmc *RepoMetaCreate) createSpec() (*RepoMeta, *sqlgraph.CreateSpec) {
	var (
		_node = &RepoMeta{config: rmc.config}
		_spec = sqlgraph.NewCreateSpec(repometa.Table, sqlgraph.NewFieldSpec(repometa.FieldID, field.TypeInt))
	)
	if value, ok := rmc.mutation.Repo(); ok {
		_spec.SetField(repometa.FieldRepo, field.TypeString, value)
		_node.Repo = value
	}
	if value, ok := rmc.mutation.LatestTag(); ok {
		_spec.SetField(repometa.FieldLatestTag, field.TypeString, value)
		_node.LatestTag = value
	}
	if value, ok := rmc.mutation.TagCount(); ok {
		_spec.SetField(repometa.FieldTagCount, field.TypeInt, value)
		_node.TagCount = value
	}
	if value, ok := rmc.mutation.Size(); ok {
		_spec.SetField(repometa.FieldSize, field.TypeInt64, value)
		_node.Size = value
	}
	if value, ok := rmc.mutation.Created(); ok {
		_spec.SetField(repometa.FieldCreated, field.TypeString, value)
		_node.Created = value
	}
	if value, ok := rmc.mutation.Platforms(); ok {
		_spec.SetField(repometa.FieldPlatforms, field.TypeJSON, value)
		_node.Platforms = value
	}
	if value, ok := rmc.mutation.PullCount(); ok {
		_spec.SetField(repometa.FieldPullCount, field.TypeInt64, value)
		_node.PullCount = value
	}
	if value, ok := rmc.mutation.LastPulledAt(); ok {
		_spec.SetField(repometa.FieldLastPulledAt, field.TypeTime, value)
		_node.LastPulledAt = &value
	}
	if value, ok := rmc.mutation.RefreshedAt(); ok {
		_spec.SetField(repometa.FieldRefreshedAt, field.TypeTime, value)
		_node.RefreshedAt = value
	}
	return _node, _spec
}

// RepoMetaCreateBulk is the builder for creating many RepoMeta entities in bulk.
type RepoMetaCreateBulk struct {
	config
	err      error
	builders []*RepoMetaCreate
}

// Save creates the RepoMeta entities in the database.
func (rmcb *RepoMetaCreateBulk) Save(ctx context.Context) ([]*RepoMeta, error) {
	if rmcb.err != nil {
		return nil, rmcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(rmcb.builders))
	nodes := make([]*RepoMeta, len(rmcb.builders))
	mutators := make([]Mutator, len(rmcb.builders))
	for i := range rmcb.builders {
		func(i int, root context.Context) {
			builder := rmcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RepoMetaMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, rmcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, rmcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, rmcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (rmcb *RepoMetaCreateBulk) SaveX(ctx context.Context) []*RepoMeta {
	v, err := rmcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rmcb *RepoMetaCreateBulk) Exec(ctx context.Context) error {
	_, err := rmcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rmcb *RepoMetaCreateBulk) ExecX(ctx context.Context) {
	if err := rmcb.Exec(ctx); err != nil {
		panic(err)
	}
}
