// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/internal/data/ent/repopermission"
	"api/internal/data/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RepoPermissionCreate is the builder for creating a RepoPermission entity.
type RepoPermissionCreate struct {
	config
	mutation *RepoPermissionMutation
	hooks    []Hook
}

// SetRepoPattern sets the "repo_pattern" field.
func (rpc *RepoPermissionCreate) SetRepoPattern(s string) *RepoPermissionCreate {
	rpc.mutation.SetRepoPattern(s)
	return rpc
}

// SetCreatedAt sets the "created_at" field.
func (rpc *RepoPermissionCreate) SetCreatedAt(t time.Time) *RepoPermissionCreate {
	rpc.mutation.SetCreatedAt(t)
	return rpc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (rpc *RepoPermissionCreate) SetNillableCreatedAt(t *time.Time) *RepoPermissionCreate {
	if t != nil {
		rpc.SetCreatedAt(*t)
	}
	return rpc
}

// SetUserID sets the "user" edge to the User entity by ID.
func (rpc *RepoPermissionCreate) SetUserID(id int) *RepoPermissionCreate {
	rpc.mutation.SetUserID(id)
	return rpc
}

// SetUser sets the "user" edge to the User entity.
func (rpc *RepoPermissionCreate) SetUser(u *User) *RepoPermissionCreate {
	return rpc.SetUserID(u.ID)
}

// Mutation returns the RepoPermissionMutation object of the builder.
func (rpc *RepoPermissionCreate) Mutation() *RepoPermissionMutation {
	return rpc.mutation
}

// Save creates the RepoPermission in the database.
func (rpc *RepoPermissionCreate) Save(ctx context.Context) (*RepoPermission, error) {
	rpc.defaults()
	return withHooks(ctx, rpc.sqlSave, rpc.mutation, rpc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (rpc *RepoPermissionCreate) SaveX(ctx context.Context) *RepoPermission {
	v, err := rpc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rpc *RepoPermissionCreate) Exec(ctx context.Context) error {
	_, err := rpc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rpc *RepoPermissionCreate) ExecX(ctx context.Context) {
	if err := rpc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (rpc *RepoPermissionCreate) defaults() {
	if _, ok := rpc.mutation.CreatedAt(); !ok {
		v := repopermission.DefaultCreatedAt()
		rpc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rpc *RepoPermissionCreate) check() error {
	if _, ok := rpc.mutation.RepoPattern(); !ok {
		return &ValidationError{Name: "repo_pattern", err: errors.New(`ent: missing required field "RepoPermission.repo_pattern"`)}
	}
	if v, ok := rpc.mutation.RepoPattern(); ok {
		if err := repopermission.RepoPatternValidator(v); err != nil {
			return &ValidationError{Name: "repo_pattern", err: fmt.Errorf(`ent: validator failed for field "RepoPermission.repo_pattern": %w`, err)}
		}
	}
	if _, ok := rpc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RepoPermission.created_at"`)}
	}
	if len(rpc.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "RepoPermission.user"`)}
	}
	return nil
}

func (rpc *RepoPermissionCreate) sqlSave(ctx context.Context) (*RepoPermission, error) {
	if err := rpc.check(); err != nil {
		return nil, err
	}
	_node, _spec := rpc.createSpec()
	if err := sqlgraph.CreateNode(ctx, rpc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	rpc.mutation.id = &_node.ID
	rpc.mutation.done = true
	return _node, nil
}

func (rpc *RepoPermissionCreate) createSpec() (*RepoPermission, *sqlgraph.CreateSpec) {
	var (
		_node = &RepoPermission{config: rpc.config}
		_spec = sqlgraph.NewCreateSpec(repopermission.Table, sqlgraph.NewFieldSpec(repopermission.FieldID, field.TypeInt))
	)
	if value, ok := rpc.mutation.RepoPattern(); ok {
		_spec.SetField(repopermission.FieldRepoPattern, field.TypeString, value)
		_node.RepoPattern = value
	}
	if value, ok := rpc.mutation.CreatedAt(); ok {
		_spec.SetField(repopermission.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := rpc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   repopermission.UserTable,
			Columns: []string{repopermission.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_permissions = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// RepoPermissionCreateBulk is the builder for creating many RepoPermission entities in bulk.
type RepoPermissionCreateBulk struct {
	config
	err      error
	builders []*RepoPermissionCreate
}

// Save creates the RepoPermission entities in the database.
func (rpcb *RepoPermissionCreateBulk) Save(ctx context.Context) ([]*RepoPermission, error) {
	if rpcb.err != nil {
		return nil, rpcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(rpcb.builders))
	nodes := make([]*RepoPermission, len(rpcb.builders))
	mutators := make([]Mutator, len(rpcb.builders))
	for i := range rpcb.builders {
		func(i int, root context.Context) {
			builder := rpcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RepoPermissionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, rpcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, rpcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, rpcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (rpcb *RepoPermissionCreateBulk) SaveX(ctx context.Context) []*RepoPermission {
	v, err := rpcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rpcb *RepoPermissionCreateBulk) Exec(ctx context.Context) error {
	_, err := rpcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rpcb *RepoPermissionCreateBulk) ExecX(ctx context.Context) {
	if err := rpcb.Exec(ctx); err != nil {
		panic(err)
	}
}
