// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/internal/data/ent/predicate"
	"api/internal/data/ent/repometa"
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RepoMetaQuery is the builder for querying RepoMeta entities.
type RepoMetaQuery struct {
	config
	ctx        *QueryContext
	order      []repometa.OrderOption
	inters     []Interceptor
	predicates []predicate.RepoMeta
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RepoMetaQuery builder.
func (rmq *RepoMetaQuery) Where(ps ...predicate.RepoMeta) *RepoMetaQuery {
	rmq.predicates = append(rmq.predicates, ps...)
	return rmq
}

// Limit the number of records to be returned by this query.
func (rmq *RepoMetaQuery) Limit(limit int) *RepoMetaQuery {
	rmq.ctx.Limit = &limit
	return rmq
}

// Offset to start from.
func (rmq *RepoMetaQuery) Offset(offset int) *RepoMetaQuery {
	rmq.ctx.Offset = &offset
	return rmq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (rmq *RepoMetaQuery) Unique(unique bool) *RepoMetaQuery {
	rmq.ctx.Unique = &unique
	return rmq
}

// Order specifies how the records should be ordered.
func (rmq *RepoMetaQuery) Order(o ...repometa.OrderOption) *RepoMetaQuery {
	rmq.order = append(rmq.order, o...)
	return rmq
}

// First returns the first RepoMeta entity from the query.
// Returns a *NotFoundError when no RepoMeta was found.
func (rmq *RepoMetaQuery) First(ctx context.Context) (*RepoMeta, error) {
	nodes, err := rmq.Limit(1).All(setContextOp(ctx, rmq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{repometa.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (rmq *RepoMetaQuery) FirstX(ctx context.Context) *RepoMeta {
	node, err := rmq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first RepoMeta ID from the query.
// Returns a *NotFoundError when no RepoMeta ID was found.
func (rmq *RepoMetaQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rmq.Limit(1).IDs(setContextOp(ctx, rmq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{repometa.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (rmq *RepoMetaQuery) FirstIDX(ctx context.Context) int {
	id, err := rmq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single RepoMeta entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one RepoMeta entity is found.
// Returns a *NotFoundError when no RepoMeta entities are found.
func (rmq *RepoMetaQuery) Only(ctx context.Context) (*RepoMeta, error) {
	nodes, err := rmq.Limit(2).All(setContextOp(ctx, rmq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{repometa.Label}
	default:
		return nil, &NotSingularError{repometa.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (rmq *RepoMetaQuery) OnlyX(ctx context.Context) *RepoMeta {
	node, err := rmq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only RepoMeta ID in the query.
// Returns a *NotSingularError when more than one RepoMeta ID is found.
// Returns a *NotFoundError when no entities are found.
func (rmq *RepoMetaQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rmq.Limit(2).IDs(setContextOp(ctx, rmq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{repometa.Label}
	default:
		err = &NotSingularError{repometa.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (rmq *RepoMetaQuery) OnlyIDX(ctx context.Context) int {
	id, err := rmq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of RepoMetaSlice.
func (rmq *RepoMetaQuery) All(ctx context.Context) ([]*RepoMeta, error) {
	ctx = setContextOp(ctx, rmq.ctx, ent.OpQueryAll)
	if err := rmq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*RepoMeta, *RepoMetaQuery]()
	return withInterceptors[[]*RepoMeta](ctx, rmq, qr, rmq.inters)
}

// AllX is like All, but panics if an error occurs.
func (rmq *RepoMetaQuery) AllX(ctx context.Context) []*RepoMeta {
	nodes, err := rmq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of RepoMeta IDs.
func (rmq *RepoMetaQuery) IDs(ctx context.Context) (ids []int, err error) {
	if rmq.ctx.Unique == nil && rmq.path != nil {
		rmq.Unique(true)
	}
	ctx = setContextOp(ctx, rmq.ctx, ent.OpQueryIDs)
	if err = rmq.Select(repometa.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (rmq *RepoMetaQuery) IDsX(ctx context.Context) []int {
	ids, err := rmq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (rmq *RepoMetaQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, rmq.ctx, ent.OpQueryCount)
	if err := rmq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, rmq, querierCount[*RepoMetaQuery](), rmq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (rmq *RepoMetaQuery) CountX(ctx context.Context) int {
	count, err := rmq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (rmq *RepoMetaQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, rmq.ctx, ent.OpQueryExist)
	switch _, err := rmq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (rmq *RepoMetaQuery) ExistX(ctx context.Context) bool {
	exist, err := rmq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RepoMetaQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (rmq *RepoMetaQuery) Clone() *RepoMetaQuery {
	if rmq == nil {
		return nil
	}
	return &RepoMetaQuery{
		config:     rmq.config,
		ctx:        rmq.ctx.Clone(),
		order:      append([]repometa.OrderOption{}, rmq.order...),
		inters:     append([]Interceptor{}, rmq.inters...),
		predicates: append([]predicate.RepoMeta{}, rmq.predicates...),
		// clone intermediate query.
		sql:  rmq.sql.Clone(),
		path: rmq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Repo string `json:"repo,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.RepoMeta.Query().
//		GroupBy(repometa.FieldRepo).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (rmq *RepoMetaQuery) GroupBy(field string, fields ...string) *RepoMetaGroupBy {
	rmq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &RepoMetaGroupBy{build: rmq}
	grbuild.flds = &rmq.ctx.Fields
	grbuild.label = repometa.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Repo string `json:"repo,omitempty"`
//	}
//
//	client.RepoMeta.Query().
//		Select(repometa.FieldRepo).
//		Scan(ctx, &v)
func (rmq *RepoMetaQuery) Select(fields ...string) *RepoMetaSelect {
	rmq.ctx.Fields = append(rmq.ctx.Fields, fields...)
	sbuild := &RepoMetaSelect{RepoMetaQuery: rmq}
	sbuild.label = repometa.Label
	sbuild.flds, sbuild.scan = &rmq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a RepoMetaSelect configured with the given aggregations.
func (rmq *RepoMetaQuery) Aggregate(fns ...AggregateFunc) *RepoMetaSelect {
	return rmq.Select().Aggregate(fns...)
}

func (rmq *RepoMetaQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range rmq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, rmq); err != nil {
				return err
			}
		}
	}
	for _, f := range rmq.ctx.Fields {
		if !repometa.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if rmq.path != nil {
		prev, err := rmq.path(ctx)
		if err != nil {
			return err
		}
		rmq.sql = prev
	}
	return nil
}

func (rmq *RepoMetaQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*RepoMeta, error) {
	var (
		nodes = []*RepoMeta{}
		_spec = rmq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*RepoMeta).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &RepoMeta{config: rmq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, rmq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (rmq *RepoMetaQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := rmq.querySpec()
	_spec.Node.Columns = rmq.ctx.Fields
	if len(rmq.ctx.Fields) > 0 {
		_spec.Unique = rmq.ctx.Unique != nil && *rmq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, rmq.driver, _spec)
}

func (rmq *RepoMetaQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(repometa.Table, repometa.Columns, sqlgraph.NewFieldSpec(repometa.FieldID, field.TypeInt))
	_spec.From = rmq.sql
	if unique := rmq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if rmq.path != nil {
		_spec.Unique = true
	}
	if fields := rmq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, repometa.FieldID)
		for i := range fields {
			if fields[i] != repometa.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := rmq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := rmq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := rmq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := rmq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (rmq *RepoMetaQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(rmq.driver.Dialect())
	t1 := builder.Table(repometa.Table)
	columns := rmq.ctx.Fields
	if len(columns) == 0 {
		columns = repometa.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if rmq.sql != nil {
		selector = rmq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if rmq.ctx.Unique != nil && *rmq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range rmq.predicates {
		p(selector)
	}
	for _, p := range rmq.order {
		p(selector)
	}
	if offset := rmq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := rmq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// RepoMetaGroupBy is the group-by builder for RepoMeta entities.
type RepoMetaGroupBy struct {
	selector
	build *RepoMetaQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rmgb *RepoMetaGroupBy) Aggregate(fns ...AggregateFunc) *RepoMetaGroupBy {
	rmgb.fns = append(rmgb.fns, fns...)
	return rmgb
}

// Scan applies the selector query and scans the result into the given value.
func (rmgb *RepoMetaGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rmgb.build.ctx, ent.OpQueryGroupBy)
	if err := rmgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RepoMetaQuery, *RepoMetaGroupBy](ctx, rmgb.build, rmgb, rmgb.build.inters, v)
}

func (rmgb *RepoMetaGroupBy) sqlScan(ctx context.Context, root *RepoMetaQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(rmgb.fns))
	for _, fn := range rmgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*rmgb.flds)+len(rmgb.fns))
		for _, f := range *rmgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*rmgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rmgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// RepoMetaSelect is the builder for selecting fields of RepoMeta entities.
type RepoMetaSelect struct {
	*RepoMetaQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (rms *RepoMetaSelect) Aggregate(fns ...AggregateFunc) *RepoMetaSelect {
	rms.fns = append(rms.fns, fns...)
	return rms
}

// Scan applies the selector query and scans the result into the given value.
func (rms *RepoMetaSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rms.ctx, ent.OpQuerySelect)
	if err := rms.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RepoMetaQuery, *RepoMetaSelect](ctx, rms.RepoMetaQuery, rms, rms.inters, v)
}

func (rms *RepoMetaSelect) sqlScan(ctx context.Context, root *RepoMetaQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(rms.fns))
	for _, fn := range rms.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*rms.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rms.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
