// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/internal/data/ent/predicate"
	"api/internal/data/ent/repopermission"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RepoPermissionDelete is the builder for deleting a RepoPermission entity.
type RepoPermissionDelete struct {
	config
	hooks    []Hook
	mutation *RepoPermissionMutation
}

// Where appends a list predicates to the RepoPermissionDelete builder.
func (rpd *RepoPermissionDelete) Where(ps ...predicate.RepoPermission) *RepoPermissionDelete {
	rpd.mutation.Where(ps...)
	return rpd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (rpd *RepoPermissionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, rpd.sqlExec, rpd.mutation, rpd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (rpd *RepoPermissionDelete) ExecX(ctx context.Context) int {
	n, err := rpd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (rpd *RepoPermissionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(repopermission.Table, sqlgraph.NewFieldSpec(repopermission.FieldID, field.TypeInt))
	if ps := rpd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, rpd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	rpd.mutation.done = true
	return affected, err
}

// RepoPermissionDeleteOne is the builder for deleting a single RepoPermission entity.
type RepoPermissionDeleteOne struct {
	rpd *RepoPermissionDelete
}

// Where appends a list predicates to the RepoPermissionDelete builder.
func (rpdo *RepoPermissionDeleteOne) Where(ps ...predicate.RepoPermission) *RepoPermissionDeleteOne {
	rpdo.rpd.mutation.Where(ps...)
	return rpdo
}

// Exec executes the deletion query.
func (rpdo *RepoPermissionDeleteOne) Exec(ctx context.Context) error {
	n, err := rpdo.rpd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{repopermission.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (rpdo *RepoPermissionDeleteOne) ExecX(ctx context.Context) {
	if err := rpdo.Exec(ctx); err != nil {
		panic(err)
	}
}
