// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/internal/data/ent/auditlog"
	"api/internal/data/ent/repometa"
	"api/internal/data/ent/repopermission"
	"api/internal/data/ent/schema"
	"api/internal/data/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	auditlogFields := schema.AuditLog{}.Fields()
	_ = auditlogFields
	// auditlogDescTs is the schema descriptor for ts field.
	auditlogDescTs := auditlogFields[0].Descriptor()
	// auditlog.DefaultTs holds the default value on creation for the ts field.
	auditlog.DefaultTs = auditlogDescTs.Default.(func() time.Time)
	// auditlogDescActor is the schema descriptor for actor field.
	auditlogDescActor := auditlogFields[1].Descriptor()
	// auditlog.ActorValidator is a validator for the "actor" field. It is called by the builders before save.
	auditlog.ActorValidator = auditlogDescActor.Validators[0].(func(string) error)
	// auditlogDescAction is the schema descriptor for action field.
	auditlogDescAction := auditlogFields[2].Descriptor()
	// auditlog.ActionValidator is a validator for the "action" field. It is called by the builders before save.
	auditlog.ActionValidator = auditlogDescAction.Validators[0].(func(string) error)
	// auditlogDescSuccess is the schema descriptor for success field.
	auditlogDescSuccess := auditlogFields[6].Descriptor()
	// auditlog.DefaultSuccess holds the default value on creation for the success field.
	auditlog.DefaultSuccess = auditlogDescSuccess.Default.(bool)
	repometaFields := schema.RepoMeta{}.Fields()
	_ = repometaFields
	// repometaDescRepo is the schema descriptor for repo field.
	repometaDescRepo := repometaFields[0].Descriptor()
	// repometa.RepoValidator is a validator for the "repo" field. It is called by the builders before save.
	repometa.RepoValidator = repometaDescRepo.Validators[0].(func(string) error)
	// repometaDescTagCount is the schema descriptor for tag_count field.
	repometaDescTagCount := repometaFields[2].Descriptor()
	// repometa.DefaultTagCount holds the default value on creation for the tag_count field.
	repometa.DefaultTagCount = repometaDescTagCount.Default.(int)
	// repometaDescSize is the schema descriptor for size field.
	repometaDescSize := repometaFields[3].Descriptor()
	// repometa.DefaultSize holds the default value on creation for the size field.
	repometa.DefaultSize = repometaDescSize.Default.(int64)
	// repometaDescPullCount is the schema descriptor for pull_count field.
	repometaDescPullCount := repometaFields[6].Descriptor()
	// repometa.DefaultPullCount holds the default value on creation for the pull_count field.
	repometa.DefaultPullCount = repometaDescPullCount.Default.(int64)
	// repometaDescRefreshedAt is the schema descriptor for refreshed_at field.
	repometaDescRefreshedAt := repometaFields[8].Descriptor()
	// repometa.DefaultRefreshedAt holds the default value on creation for the refreshed_at field.
	repometa.DefaultRefreshedAt = repometaDescRefreshedAt.Default.(func() time.Time)
	// repometa.UpdateDefaultRefreshedAt holds the default value on update for the refreshed_at field.
	repometa.UpdateDefaultRefreshedAt = repometaDescRefreshedAt.UpdateDefault.(func() time.Time)
	repopermissionFields := schema.RepoPermission{}.Fields()
	_ = repopermissionFields
	// repopermissionDescRepoPattern is the schema descriptor for repo_pattern field.
	repopermissionDescRepoPattern := repopermissionFields[0].Descriptor()
	// repopermission.RepoPatternValidator is a validator for the "repo_pattern" field. It is called by the builders before save.
	repopermission.RepoPatternValidator = repopermissionDescRepoPattern.Validators[0].(func(string) error)
	// repopermissionDescCreatedAt is the schema descriptor for created_at field.
	repopermissionDescCreatedAt := repopermissionFields[1].Descriptor()
	// repopermission.DefaultCreatedAt holds the default value on creation for the created_at field.
	repopermission.DefaultCreatedAt = repopermissionDescCreatedAt.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[0].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[1].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = userDescPasswordHash.Validators[0].(func(string) error)
	// userDescDisabled is the schema descriptor for disabled field.
	userDescDisabled := userFields[3].Descriptor()
	// user.DefaultDisabled holds the default value on creation for the disabled field.
	user.DefaultDisabled = userDescDisabled.Default.(bool)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[4].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[5].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
}
