// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/internal/data/ent/systemsetting"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SystemSettingCreate is the builder for creating a SystemSetting entity.
type SystemSettingCreate struct {
	config
	mutation *SystemSettingMutation
	hooks    []Hook
}

// SetKey sets the "key" field.
func (ssc *SystemSettingCreate) SetKey(s string) *SystemSettingCreate {
	ssc.mutation.SetKey(s)
	return ssc
}

// SetValue sets the "value" field.
func (ssc *SystemSettingCreate) SetValue(jm json.RawMessage) *SystemSettingCreate {
	ssc.mutation.SetValue(jm)
	return ssc
}

// SetVersion sets the "version" field.
func (ssc *SystemSettingCreate) SetVersion(i int64) *SystemSettingCreate {
	ssc.mutation.SetVersion(i)
	return ssc
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (ssc *SystemSettingCreate) SetNillableVersion(i *int64) *SystemSettingCreate {
	if i != nil {
		ssc.SetVersion(*i)
	}
	return ssc
}

// SetUpdatedAt sets the "updated_at" field.
func (ssc *SystemSettingCreate) SetUpdatedAt(t time.Time) *SystemSettingCreate {
	ssc.mutation.SetUpdatedAt(t)
	return ssc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (ssc *SystemSettingCreate) SetNillableUpdatedAt(t *time.Time) *SystemSettingCreate {
	if t != nil {
		ssc.SetUpdatedAt(*t)
	}
	return ssc
}

// SetUpdatedBy sets the "updated_by" field.
func (ssc *SystemSettingCreate) SetUpdatedBy(s string) *SystemSettingCreate {
	ssc.mutation.SetUpdatedBy(s)
	return ssc
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (ssc *SystemSettingCreate) SetNillableUpdatedBy(s *string) *SystemSettingCreate {
	if s != nil {
		ssc.SetUpdatedBy(*s)
	}
	return ssc
}

// Mutation returns the SystemSettingMutation object of the builder.
func (ssc *SystemSettingCreate) Mutation() *SystemSettingMutation {
	return ssc.mutation
}

// Save creates the SystemSetting in the database.
func (ssc *SystemSettingCreate) Save(ctx context.Context) (*SystemSetting, error) {
	ssc.defaults()
	return withHooks(ctx, ssc.sqlSave, ssc.mutation, ssc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ssc *SystemSettingCreate) SaveX(ctx context.Context) *SystemSetting {
	v, err := ssc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ssc *SystemSettingCreate) Exec(ctx context.Context) error {
	_, err := ssc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ssc *SystemSettingCreate) ExecX(ctx context.Context) {
	if err := ssc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ssc *SystemSettingCreate) defaults() {
	if _, ok := ssc.mutation.Version(); !ok {
		v := systemsetting.DefaultVersion
		ssc.mutation.SetVersion(v)
	}
	if _, ok := ssc.mutation.UpdatedAt(); !ok {
		v := systemsetting.DefaultUpdatedAt()
		ssc.mutation.SetUpdatedAt(v)
	}
	if _, ok := ssc.mutation.UpdatedBy(); !ok {
		v := systemsetting.DefaultUpdatedBy
		ssc.mutation.SetUpdatedBy(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ssc *SystemSettingCreate) check() error {
	if _, ok := ssc.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "SystemSetting.key"`)}
	}
	if v, ok := ssc.mutation.Key(); ok {
		if err := systemsetting.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "SystemSetting.key": %w`, err)}
		}
	}
	if _, ok := ssc.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`ent: missing required field "SystemSetting.value"`)}
	}
	if _, ok := ssc.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "SystemSetting.version"`)}
	}
	if v, ok := ssc.mutation.Version(); ok {
		if err := systemsetting.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "SystemSetting.version": %w`, err)}
		}
	}
	if _, ok := ssc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SystemSetting.updated_at"`)}
	}
	if _, ok := ssc.mutation.UpdatedBy(); !ok {
		return &ValidationError{Name: "updated_by", err: errors.New(`ent: missing required field "SystemSetting.updated_by"`)}
	}
	if v, ok := ssc.mutation.UpdatedBy(); ok {
		if err := systemsetting.UpdatedByValidator(v); err != nil {
			return &ValidationError{Name: "updated_by", err: fmt.Errorf(`ent: validator failed for field "SystemSetting.updated_by": %w`, err)}
		}
	}
	return nil
}

func (ssc *SystemSettingCreate) sqlSave(ctx context.Context) (*SystemSetting, error) {
	if err := ssc.check(); err != nil {
		return nil, err
	}
	_node, _spec := ssc.createSpec()
	if err := sqlgraph.CreateNode(ctx, ssc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	ssc.mutation.id = &_node.ID
	ssc.mutation.done = true
	return _node, nil
}

func (ssc *SystemSettingCreate) createSpec() (*SystemSetting, *sqlgraph.CreateSpec) {
	var (
		_node = &SystemSetting{config: ssc.config}
		_spec = sqlgraph.NewCreateSpec(systemsetting.Table, sqlgraph.NewFieldSpec(systemsetting.FieldID, field.TypeInt))
	)
	if value, ok := ssc.mutation.Key(); ok {
		_spec.SetField(systemsetting.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := ssc.mutation.Value(); ok {
		_spec.SetField(systemsetting.FieldValue, field.TypeJSON, value)
		_node.Value = value
	}
	if value, ok := ssc.mutation.Version(); ok {
		_spec.SetField(systemsetting.FieldVersion, field.TypeInt64, value)
		_node.Version = value
	}
	if value, ok := ssc.mutation.UpdatedAt(); ok {
		_spec.SetField(systemsetting.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := ssc.mutation.UpdatedBy(); ok {
		_spec.SetField(systemsetting.FieldUpdatedBy, field.TypeString, value)
		_node.UpdatedBy = value
	}
	return _node, _spec
}

// SystemSettingCreateBulk is the builder for creating many SystemSetting entities in bulk.
type SystemSettingCreateBulk struct {
	config
	err      error
	builders []*SystemSettingCreate
}

// Save creates the SystemSetting entities in the database.
func (sscb *SystemSettingCreateBulk) Save(ctx context.Context) ([]*SystemSetting, error) {
	if sscb.err != nil {
		return nil, sscb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(sscb.builders))
	nodes := make([]*SystemSetting, len(sscb.builders))
	mutators := make([]Mutator, len(sscb.builders))
	for i := range sscb.builders {
		func(i int, root context.Context) {
			builder := sscb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SystemSettingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, sscb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, sscb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, sscb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (sscb *SystemSettingCreateBulk) SaveX(ctx context.Context) []*SystemSetting {
	v, err := sscb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sscb *SystemSettingCreateBulk) Exec(ctx context.Context) error {
	_, err := sscb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sscb *SystemSettingCreateBulk) ExecX(ctx context.Context) {
	if err := sscb.Exec(ctx); err != nil {
		panic(err)
	}
}
