// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/internal/data/ent/predicate"
	"api/internal/data/ent/systemsetting"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// SystemSettingUpdate is the builder for updating SystemSetting entities.
type SystemSettingUpdate struct {
	config
	hooks    []Hook
	mutation *SystemSettingMutation
}

// Where appends a list predicates to the SystemSettingUpdate builder.
func (ssu *SystemSettingUpdate) Where(ps ...predicate.SystemSetting) *SystemSettingUpdate {
	ssu.mutation.Where(ps...)
	return ssu
}

// SetValue sets the "value" field.
func (ssu *SystemSettingUpdate) SetValue(jm json.RawMessage) *SystemSettingUpdate {
	ssu.mutation.SetValue(jm)
	return ssu
}

// AppendValue appends jm to the "value" field.
func (ssu *SystemSettingUpdate) AppendValue(jm json.RawMessage) *SystemSettingUpdate {
	ssu.mutation.AppendValue(jm)
	return ssu
}

// SetVersion sets the "version" field.
func (ssu *SystemSettingUpdate) SetVersion(i int64) *SystemSettingUpdate {
	ssu.mutation.ResetVersion()
	ssu.mutation.SetVersion(i)
	return ssu
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (ssu *SystemSettingUpdate) SetNillableVersion(i *int64) *SystemSettingUpdate {
	if i != nil {
		ssu.SetVersion(*i)
	}
	return ssu
}

// AddVersion adds i to the "version" field.
func (ssu *SystemSettingUpdate) AddVersion(i int64) *SystemSettingUpdate {
	ssu.mutation.AddVersion(i)
	return ssu
}

// SetUpdatedAt sets the "updated_at" field.
func (ssu *SystemSettingUpdate) SetUpdatedAt(t time.Time) *SystemSettingUpdate {
	ssu.mutation.SetUpdatedAt(t)
	return ssu
}

// SetUpdatedBy sets the "updated_by" field.
func (ssu *SystemSettingUpdate) SetUpdatedBy(s string) *SystemSettingUpdate {
	ssu.mutation.SetUpdatedBy(s)
	return ssu
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (ssu *SystemSettingUpdate) SetNillableUpdatedBy(s *string) *SystemSettingUpdate {
	if s != nil {
		ssu.SetUpdatedBy(*s)
	}
	return ssu
}

// Mutation returns the SystemSettingMutation object of the builder.
func (ssu *SystemSettingUpdate) Mutation() *SystemSettingMutation {
	return ssu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ssu *SystemSettingUpdate) Save(ctx context.Context) (int, error) {
	ssu.defaults()
	return withHooks(ctx, ssu.sqlSave, ssu.mutation, ssu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ssu *SystemSettingUpdate) SaveX(ctx context.Context) int {
	affected, err := ssu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ssu *SystemSettingUpdate) Exec(ctx context.Context) error {
	_, err := ssu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ssu *SystemSettingUpdate) ExecX(ctx context.Context) {
	if err := ssu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ssu *SystemSettingUpdate) defaults() {
	if _, ok := ssu.mutation.UpdatedAt(); !ok {
		v := systemsetting.UpdateDefaultUpdatedAt()
		ssu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ssu *SystemSettingUpdate) check() error {
	if v, ok := ssu.mutation.Version(); ok {
		if err := systemsetting.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "SystemSetting.version": %w`, err)}
		}
	}
	if v, ok := ssu.mutation.UpdatedBy(); ok {
		if err := systemsetting.UpdatedByValidator(v); err != nil {
			return &ValidationError{Name: "updated_by", err: fmt.Errorf(`ent: validator failed for field "SystemSetting.updated_by": %w`, err)}
		}
	}
	return nil
}

func (ssu *SystemSettingUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ssu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(systemsetting.Table, systemsetting.Columns, sqlgraph.NewFieldSpec(systemsetting.FieldID, field.TypeInt))
	if ps := ssu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ssu.mutation.Value(); ok {
		_spec.SetField(systemsetting.FieldValue, field.TypeJSON, value)
	}
	if value, ok := ssu.mutation.AppendedValue(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, systemsetting.FieldValue, value)
		})
	}
	if value, ok := ssu.mutation.Version(); ok {
		_spec.SetField(systemsetting.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := ssu.mutation.AddedVersion(); ok {
		_spec.AddField(systemsetting.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := ssu.mutation.UpdatedAt(); ok {
		_spec.SetField(systemsetting.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := ssu.mutation.UpdatedBy(); ok {
		_spec.SetField(systemsetting.FieldUpdatedBy, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ssu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{systemsetting.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ssu.mutation.done = true
	return n, nil
}

// SystemSettingUpdateOne is the builder for updating a single SystemSetting entity.
type SystemSettingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SystemSettingMutation
}

// SetValue sets the "value" field.
func (ssuo *SystemSettingUpdateOne) SetValue(jm json.RawMessage) *SystemSettingUpdateOne {
	ssuo.mutation.SetValue(jm)
	return ssuo
}

// AppendValue appends jm to the "value" field.
func (ssuo *SystemSettingUpdateOne) AppendValue(jm json.RawMessage) *SystemSettingUpdateOne {
	ssuo.mutation.AppendValue(jm)
	return ssuo
}

// SetVersion sets the "version" field.
func (ssuo *SystemSettingUpdateOne) SetVersion(i int64) *SystemSettingUpdateOne {
	ssuo.mutation.ResetVersion()
	ssuo.mutation.SetVersion(i)
	return ssuo
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (ssuo *SystemSettingUpdateOne) SetNillableVersion(i *int64) *SystemSettingUpdateOne {
	if i != nil {
		ssuo.SetVersion(*i)
	}
	return ssuo
}

// AddVersion adds i to the "version" field.
func (ssuo *SystemSettingUpdateOne) AddVersion(i int64) *SystemSettingUpdateOne {
	ssuo.mutation.AddVersion(i)
	return ssuo
}

// SetUpdatedAt sets the "updated_at" field.
func (ssuo *SystemSettingUpdateOne) SetUpdatedAt(t time.Time) *SystemSettingUpdateOne {
	ssuo.mutation.SetUpdatedAt(t)
	return ssuo
}

// SetUpdatedBy sets the "updated_by" field.
func (ssuo *SystemSettingUpdateOne) SetUpdatedBy(s string) *SystemSettingUpdateOne {
	ssuo.mutation.SetUpdatedBy(s)
	return ssuo
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (ssuo *SystemSettingUpdateOne) SetNillableUpdatedBy(s *string) *SystemSettingUpdateOne {
	if s != nil {
		ssuo.SetUpdatedBy(*s)
	}
	return ssuo
}

// Mutation returns the SystemSettingMutation object of the builder.
func (ssuo *SystemSettingUpdateOne) Mutation() *SystemSettingMutation {
	return ssuo.mutation
}

// Where appends a list predicates to the SystemSettingUpdate builder.
func (ssuo *SystemSettingUpdateOne) Where(ps ...predicate.SystemSetting) *SystemSettingUpdateOne {
	ssuo.mutation.Where(ps...)
	return ssuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ssuo *SystemSettingUpdateOne) Select(field string, fields ...string) *SystemSettingUpdateOne {
	ssuo.fields = append([]string{field}, fields...)
	return ssuo
}

// Save executes the query and returns the updated SystemSetting entity.
func (ssuo *SystemSettingUpdateOne) Save(ctx context.Context) (*SystemSetting, error) {
	ssuo.defaults()
	return withHooks(ctx, ssuo.sqlSave, ssuo.mutation, ssuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ssuo *SystemSettingUpdateOne) SaveX(ctx context.Context) *SystemSetting {
	node, err := ssuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ssuo *SystemSettingUpdateOne) Exec(ctx context.Context) error {
	_, err := ssuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ssuo *SystemSettingUpdateOne) ExecX(ctx context.Context) {
	if err := ssuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ssuo *SystemSettingUpdateOne) defaults() {
	if _, ok := ssuo.mutation.UpdatedAt(); !ok {
		v := systemsetting.UpdateDefaultUpdatedAt()
		ssuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ssuo *SystemSettingUpdateOne) check() error {
	if v, ok := ssuo.mutation.Version(); ok {
		if err := systemsetting.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "SystemSetting.version": %w`, err)}
		}
	}
	if v, ok := ssuo.mutation.UpdatedBy(); ok {
		if err := systemsetting.UpdatedByValidator(v); err != nil {
			return &ValidationError{Name: "updated_by", err: fmt.Errorf(`ent: validator failed for field "SystemSetting.updated_by": %w`, err)}
		}
	}
	return nil
}

func (ssuo *SystemSettingUpdateOne) sqlSave(ctx context.Context) (_node *SystemSetting, err error) {
	if err := ssuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(systemsetting.Table, systemsetting.Columns, sqlgraph.NewFieldSpec(systemsetting.FieldID, field.TypeInt))
	id, ok := ssuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SystemSetting.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ssuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, systemsetting.FieldID)
		for _, f := range fields {
			if !systemsetting.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != systemsetting.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ssuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ssuo.mutation.Value(); ok {
		_spec.SetField(systemsetting.FieldValue, field.TypeJSON, value)
	}
	if value, ok := ssuo.mutation.AppendedValue(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, systemsetting.FieldValue, value)
		})
	}
	if value, ok := ssuo.mutation.Version(); ok {
		_spec.SetField(systemsetting.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := ssuo.mutation.AddedVersion(); ok {
		_spec.AddField(systemsetting.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := ssuo.mutation.UpdatedAt(); ok {
		_spec.SetField(systemsetting.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := ssuo.mutation.UpdatedBy(); ok {
		_spec.SetField(systemsetting.FieldUpdatedBy, field.TypeString, value)
	}
	_node = &SystemSetting{config: ssuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ssuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{systemsetting.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ssuo.mutation.done = true
	return _node, nil
}
