// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AuditLogsColumns holds the columns for the "audit_logs" table.
	AuditLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "ts", Type: field.TypeTime},
		{Name: "actor", Type: field.TypeString},
		{Name: "action", Type: field.TypeString},
		{Name: "target", Type: field.TypeString, Nullable: true},
		{Name: "scope", Type: field.TypeString, Nullable: true},
		{Name: "client_ip", Type: field.TypeString, Nullable: true},
		{Name: "success", Type: field.TypeBool, Default: true},
		{Name: "detail", Type: field.TypeJSON, Nullable: true},
	}
	// AuditLogsTable holds the schema information for the "audit_logs" table.
	AuditLogsTable = &schema.Table{
		Name:       "audit_logs",
		Columns:    AuditLogsColumns,
		PrimaryKey: []*schema.Column{AuditLogsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "auditlog_ts",
				Unique:  false,
				Columns: []*schema.Column{AuditLogsColumns[1]},
			},
			{
				Name:    "auditlog_actor",
				Unique:  false,
				Columns: []*schema.Column{AuditLogsColumns[2]},
			},
			{
				Name:    "auditlog_action",
				Unique:  false,
				Columns: []*schema.Column{AuditLogsColumns[3]},
			},
		},
	}
	// RepoPermissionsColumns holds the columns for the "repo_permissions" table.
	RepoPermissionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "repo_pattern", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "user_permissions", Type: field.TypeInt},
	}
	// RepoPermissionsTable holds the schema information for the "repo_permissions" table.
	RepoPermissionsTable = &schema.Table{
		Name:       "repo_permissions",
		Columns:    RepoPermissionsColumns,
		PrimaryKey: []*schema.Column{RepoPermissionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "repo_permissions_users_permissions",
				Columns:    []*schema.Column{RepoPermissionsColumns[3]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "repopermission_repo_pattern_user_permissions",
				Unique:  true,
				Columns: []*schema.Column{RepoPermissionsColumns[1], RepoPermissionsColumns[3]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"admin", "write", "view"}, Default: "view"},
		{Name: "disabled", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "user_username",
				Unique:  true,
				Columns: []*schema.Column{UsersColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AuditLogsTable,
		RepoPermissionsTable,
		UsersTable,
	}
)

func init() {
	RepoPermissionsTable.ForeignKeys[0].RefTable = UsersTable
}
