// Code generated by ent, DO NOT EDIT.

package repopermission

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the repopermission type in the database.
	Label = "repo_permission"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRepoPattern holds the string denoting the repo_pattern field in the database.
	FieldRepoPattern = "repo_pattern"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the repopermission in the database.
	Table = "repo_permissions"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "repo_permissions"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_permissions"
)

// Columns holds all SQL columns for repopermission fields.
var Columns = []string{
	FieldID,
	FieldRepoPattern,
	FieldCreatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "repo_permissions"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"user_permissions",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// RepoPatternValidator is a validator for the "repo_pattern" field. It is called by the builders before save.
	RepoPatternValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the RepoPermission queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRepoPattern orders the results by the repo_pattern field.
func ByRepoPattern(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRepoPattern, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
