// Code generated by ent, DO NOT EDIT.

package repopermission

import (
	"api/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.RepoPermission {
	return predicate.RepoPermission(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.RepoPermission {
	return predicate.RepoPermission(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.RepoPermission {
	return predicate.RepoPermission(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.RepoPermission {
	return predicate.RepoPermission(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.RepoPermission {
	return predicate.RepoPermission(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.RepoPermission {
	return predicate.RepoPermission(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.RepoPermission {
	return predicate.RepoPermission(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.RepoPermission {
	return predicate.RepoPermission(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.RepoPermission {
	return predicate.RepoPermission(sql.FieldLTE(FieldID, id))
}

// RepoPattern applies equality check predicate on the "repo_pattern" field. It's identical to RepoPatternEQ.
func RepoPattern(v string) predicate.RepoPermission {
	return predicate.RepoPermission(sql.FieldEQ(FieldRepoPattern, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RepoPermission {
	return predicate.RepoPermission(sql.FieldEQ(FieldCreatedAt, v))
}

// RepoPatternEQ applies the EQ predicate on the "repo_pattern" field.
func RepoPatternEQ(v string) predicate.RepoPermission {
	return predicate.RepoPermission(sql.FieldEQ(FieldRepoPattern, v))
}

// RepoPatternNEQ applies the NEQ predicate on the "repo_pattern" field.
func RepoPatternNEQ(v string) predicate.RepoPermission {
	return predicate.RepoPermission(sql.FieldNEQ(FieldRepoPattern, v))
}

// RepoPatternIn applies the In predicate on the "repo_pattern" field.
func RepoPatternIn(vs ...string) predicate.RepoPermission {
	return predicate.RepoPermission(sql.FieldIn(FieldRepoPattern, vs...))
}

// RepoPatternNotIn applies the NotIn predicate on the "repo_pattern" field.
func RepoPatternNotIn(vs ...string) predicate.RepoPermission {
	return predicate.RepoPermission(sql.FieldNotIn(FieldRepoPattern, vs...))
}

// RepoPatternGT applies the GT predicate on the "repo_pattern" field.
func RepoPatternGT(v string) predicate.RepoPermission {
	return predicate.RepoPermission(sql.FieldGT(FieldRepoPattern, v))
}

// RepoPatternGTE applies the GTE predicate on the "repo_pattern" field.
func RepoPatternGTE(v string) predicate.RepoPermission {
	return predicate.RepoPermission(sql.FieldGTE(FieldRepoPattern, v))
}

// RepoPatternLT applies the LT predicate on the "repo_pattern" field.
func RepoPatternLT(v string) predicate.RepoPermission {
	return predicate.RepoPermission(sql.FieldLT(FieldRepoPattern, v))
}

// RepoPatternLTE applies the LTE predicate on the "repo_pattern" field.
func RepoPatternLTE(v string) predicate.RepoPermission {
	return predicate.RepoPermission(sql.FieldLTE(FieldRepoPattern, v))
}

// RepoPatternContains applies the Contains predicate on the "repo_pattern" field.
func RepoPatternContains(v string) predicate.RepoPermission {
	return predicate.RepoPermission(sql.FieldContains(FieldRepoPattern, v))
}

// RepoPatternHasPrefix applies the HasPrefix predicate on the "repo_pattern" field.
func RepoPatternHasPrefix(v string) predicate.RepoPermission {
	return predicate.RepoPermission(sql.FieldHasPrefix(FieldRepoPattern, v))
}

// RepoPatternHasSuffix applies the HasSuffix predicate on the "repo_pattern" field.
func RepoPatternHasSuffix(v string) predicate.RepoPermission {
	return predicate.RepoPermission(sql.FieldHasSuffix(FieldRepoPattern, v))
}

// RepoPatternEqualFold applies the EqualFold predicate on the "repo_pattern" field.
func RepoPatternEqualFold(v string) predicate.RepoPermission {
	return predicate.RepoPermission(sql.FieldEqualFold(FieldRepoPattern, v))
}

// RepoPatternContainsFold applies the ContainsFold predicate on the "repo_pattern" field.
func RepoPatternContainsFold(v string) predicate.RepoPermission {
	return predicate.RepoPermission(sql.FieldContainsFold(FieldRepoPattern, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RepoPermission {
	return predicate.RepoPermission(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RepoPermission {
	return predicate.RepoPermission(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RepoPermission {
	return predicate.RepoPermission(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RepoPermission {
	return predicate.RepoPermission(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RepoPermission {
	return predicate.RepoPermission(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RepoPermission {
	return predicate.RepoPermission(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RepoPermission {
	return predicate.RepoPermission(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RepoPermission {
	return predicate.RepoPermission(sql.FieldLTE(FieldCreatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.RepoPermission {
	return predicate.RepoPermission(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.RepoPermission {
	return predicate.RepoPermission(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RepoPermission) predicate.RepoPermission {
	return predicate.RepoPermission(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RepoPermission) predicate.RepoPermission {
	return predicate.RepoPermission(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RepoPermission) predicate.RepoPermission {
	return predicate.RepoPermission(sql.NotPredicates(p))
}
